IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Arch_GRUNDY_Policy]') AND type in (N'U'))
DROP TABLE [dbo].[Arch_GRUNDY_Policy]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Arch_GRUNDY_Policy]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Arch_GRUNDY_Policy](
	[Arch_GRUNDY_Policy_ID] [int] IDENTITY(1,1) NOT NULL,
	[REC_NUM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_NUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUB_AGENT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCEPT_DATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXP_DATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME_INSURED] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRESS_N] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY_NAME] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_CD] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_FORM_01] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_FORM_02] [nvarchar](52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP_CODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BROKER] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BADDRESS] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BCITY_NAME] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTATE_CD] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BZIP_CODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOD_INS_EP] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOD_INS_EO] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MED_PAY_EP] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNINS_MTR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDTL_COV] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_1] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_1] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_1] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_2] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_2] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_2] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_3] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_3] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_3] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_4] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_4] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_4] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOW_LABOR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR_1] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE1] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM1] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR_2] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE2] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM2] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR_3] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE3] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE3] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM3] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR4] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE4] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE4] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM4] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO1] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO2] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO3] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO4] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_1] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_1b] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_2] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_2B] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_3] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_3B] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_4] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_4b] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISSUE_DATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST_SUR_CHG] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOT_VEHCLS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENDORSEMNT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREM_TERM] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_COM_LD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_COL_LD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_P_ADJ] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TERM_E_PRE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_TERM_P] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ID_CDS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEW_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REINST_FEE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMM_ACCT_NUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRINT_FLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXEMPT_50] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_EFF_DT] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DR_LIC_NUM] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOT_ACV] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPEC_R_COL] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPEC_R_CMP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_FLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_CODE] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REMT_P_FLG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NO_CLC_ACV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PA_TORT] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST_TERIT_C] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BROKER_COD] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIR_BILL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRVS_BDAY] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRVS_ST_LC] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordStatus] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UpdateDate] [datetime] NULL,
	[PHLINS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRVGENDER] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANSDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_Arch_GRUNDY_Policy] PRIMARY KEY CLUSTERED 
(
	[Arch_GRUNDY_Policy_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_REC_NUM]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_REC_NUM]  DEFAULT (' ') FOR [REC_NUM]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_POLICY_NUM]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_POLICY_NUM]  DEFAULT (' ') FOR [POLICY_NUM]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_SUB_AGENT]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_SUB_AGENT]  DEFAULT (' ') FOR [SUB_AGENT]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_INCEPT_DATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_INCEPT_DATE]  DEFAULT (' ') FOR [INCEPT_DATE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_EXP_DATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_EXP_DATE]  DEFAULT (' ') FOR [EXP_DATE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_NAME_INSURED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_NAME_INSURED]  DEFAULT (' ') FOR [NAME_INSURED]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ADDRESS_N]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ADDRESS_N]  DEFAULT (' ') FOR [ADDRESS_N]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_CITY_NAME]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_CITY_NAME]  DEFAULT (' ') FOR [CITY_NAME]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_STATE_CD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_STATE_CD]  DEFAULT (' ') FOR [STATE_CD]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_STATE_FORM_01]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_STATE_FORM_01]  DEFAULT (' ') FOR [STATE_FORM_01]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_STATE_FORM_02]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_STATE_FORM_02]  DEFAULT (' ') FOR [STATE_FORM_02]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ZIP_CODE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ZIP_CODE]  DEFAULT (' ') FOR [ZIP_CODE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BROKER]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BROKER]  DEFAULT (' ') FOR [BROKER]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BADDRESS]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BADDRESS]  DEFAULT (' ') FOR [BADDRESS]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BCITY_NAME]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BCITY_NAME]  DEFAULT (' ') FOR [BCITY_NAME]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BSTATE_CD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BSTATE_CD]  DEFAULT (' ') FOR [BSTATE_CD]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BZIP_CODE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BZIP_CODE]  DEFAULT (' ') FOR [BZIP_CODE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BOD_INS_EP]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BOD_INS_EP]  DEFAULT (' ') FOR [BOD_INS_EP]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BOD_INS_EO]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BOD_INS_EO]  DEFAULT (' ') FOR [BOD_INS_EO]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_MED_PAY_EP]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_MED_PAY_EP]  DEFAULT (' ') FOR [MED_PAY_EP]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_UNINS_MTR]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_UNINS_MTR]  DEFAULT (' ') FOR [UNINS_MTR]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ADDTL_COV]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ADDTL_COV]  DEFAULT (' ') FOR [ADDTL_COV]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ACV_1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ACV_1]  DEFAULT (' ') FOR [ACV_1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COMP_L_DED_1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COMP_L_DED_1]  DEFAULT (' ') FOR [COMP_L_DED_1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COLL_L_DED_1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COLL_L_DED_1]  DEFAULT (' ') FOR [COLL_L_DED_1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ACV_2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ACV_2]  DEFAULT (' ') FOR [ACV_2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COMP_L_DED_2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COMP_L_DED_2]  DEFAULT (' ') FOR [COMP_L_DED_2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COLL_L_DED_2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COLL_L_DED_2]  DEFAULT (' ') FOR [COLL_L_DED_2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ACV_3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ACV_3]  DEFAULT (' ') FOR [ACV_3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COMP_L_DED_3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COMP_L_DED_3]  DEFAULT (' ') FOR [COMP_L_DED_3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COLL_L_DED_3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COLL_L_DED_3]  DEFAULT (' ') FOR [COLL_L_DED_3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ACV_4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ACV_4]  DEFAULT (' ') FOR [ACV_4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COMP_L_DED_4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COMP_L_DED_4]  DEFAULT (' ') FOR [COMP_L_DED_4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COLL_L_DED_4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COLL_L_DED_4]  DEFAULT (' ') FOR [COLL_L_DED_4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TOW_LABOR]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TOW_LABOR]  DEFAULT (' ') FOR [TOW_LABOR]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VEH_YEAR_1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VEH_YEAR_1]  DEFAULT (' ') FOR [VEH_YEAR_1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_MAKE1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_MAKE1]  DEFAULT (' ') FOR [MAKE1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TYPE1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TYPE1]  DEFAULT (' ') FOR [TYPE1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VIN_SER_NUM1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VIN_SER_NUM1]  DEFAULT (' ') FOR [VIN_SER_NUM1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VEH_YEAR_2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VEH_YEAR_2]  DEFAULT (' ') FOR [VEH_YEAR_2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_MAKE2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_MAKE2]  DEFAULT (' ') FOR [MAKE2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TYPE2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TYPE2]  DEFAULT (' ') FOR [TYPE2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VIN_SER_NUM2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VIN_SER_NUM2]  DEFAULT (' ') FOR [VIN_SER_NUM2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VEH_YEAR_3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VEH_YEAR_3]  DEFAULT (' ') FOR [VEH_YEAR_3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_MAKE3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_MAKE3]  DEFAULT (' ') FOR [MAKE3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TYPE3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TYPE3]  DEFAULT (' ') FOR [TYPE3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VIN_SER_NUM3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VIN_SER_NUM3]  DEFAULT (' ') FOR [VIN_SER_NUM3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VEH_YEAR4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VEH_YEAR4]  DEFAULT (' ') FOR [VEH_YEAR4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_MAKE4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_MAKE4]  DEFAULT (' ') FOR [MAKE4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TYPE4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TYPE4]  DEFAULT (' ') FOR [TYPE4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VIN_SER_NUM4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VIN_SER_NUM4]  DEFAULT (' ') FOR [VIN_SER_NUM4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_GARAGE_LO1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_GARAGE_LO1]  DEFAULT (' ') FOR [GARAGE_LO1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_GARAGE_LO2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_GARAGE_LO2]  DEFAULT (' ') FOR [GARAGE_LO2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_GARAGE_LO3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_GARAGE_LO3]  DEFAULT (' ') FOR [GARAGE_LO3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_GARAGE_LO4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_GARAGE_LO4]  DEFAULT (' ') FOR [GARAGE_LO4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_1]  DEFAULT (' ') FOR [LOSS_PAY_1]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_1b]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_1b]  DEFAULT (' ') FOR [LOSS_PAY_1b]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_2]  DEFAULT (' ') FOR [LOSS_PAY_2]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_2B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_2B]  DEFAULT (' ') FOR [LOSS_PAY_2B]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_3]  DEFAULT (' ') FOR [LOSS_PAY_3]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_3B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_3B]  DEFAULT (' ') FOR [LOSS_PAY_3B]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_4]  DEFAULT (' ') FOR [LOSS_PAY_4]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_LOSS_PAY_4b]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_LOSS_PAY_4b]  DEFAULT (' ') FOR [LOSS_PAY_4b]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ISSUE_DATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ISSUE_DATE]  DEFAULT (' ') FOR [ISSUE_DATE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ST_SUR_CHG]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ST_SUR_CHG]  DEFAULT (' ') FOR [ST_SUR_CHG]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TOT_VEHCLS]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TOT_VEHCLS]  DEFAULT (' ') FOR [TOT_VEHCLS]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ENDORSEMNT]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ENDORSEMNT]  DEFAULT (' ') FOR [ENDORSEMNT]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_PREM_TERM]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_PREM_TERM]  DEFAULT (' ') FOR [PREM_TERM]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TTL_COM_LD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TTL_COM_LD]  DEFAULT (' ') FOR [TTL_COM_LD]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TTL_COL_LD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TTL_COL_LD]  DEFAULT (' ') FOR [TTL_COL_LD]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TTL_P_ADJ]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TTL_P_ADJ]  DEFAULT (' ') FOR [TTL_P_ADJ]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TERM_E_PRE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TERM_E_PRE]  DEFAULT (' ') FOR [TERM_E_PRE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TTL_TERM_P]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TTL_TERM_P]  DEFAULT (' ') FOR [TTL_TERM_P]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_POL_ID_CDS]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_POL_ID_CDS]  DEFAULT (' ') FOR [POL_ID_CDS]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_RENEW_IND]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_RENEW_IND]  DEFAULT (' ') FOR [RENEW_IND]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_REINST_FEE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_REINST_FEE]  DEFAULT (' ') FOR [REINST_FEE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_COMM_ACCT_NUM]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_COMM_ACCT_NUM]  DEFAULT (' ') FOR [COMM_ACCT_NUM]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_PRINT_FLAG]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_PRINT_FLAG]  DEFAULT (' ') FOR [PRINT_FLAG]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_EXEMPT_50]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_EXEMPT_50]  DEFAULT (' ') FOR [EXEMPT_50]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_VEH_EFF_DT]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_VEH_EFF_DT]  DEFAULT (' ') FOR [VEH_EFF_DT]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_DR_LIC_NUM]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_DR_LIC_NUM]  DEFAULT (' ') FOR [DR_LIC_NUM]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TOT_ACV]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TOT_ACV]  DEFAULT (' ') FOR [TOT_ACV]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_SPEC_R_COL]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_SPEC_R_COL]  DEFAULT (' ') FOR [SPEC_R_COL]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_SPEC_R_CMP]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_SPEC_R_CMP]  DEFAULT (' ') FOR [SPEC_R_CMP]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TRANS_FLAG]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TRANS_FLAG]  DEFAULT (' ') FOR [TRANS_FLAG]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TRANS_CODE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TRANS_CODE]  DEFAULT (' ') FOR [TRANS_CODE]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_REMT_P_FLG]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_REMT_P_FLG]  DEFAULT (' ') FOR [REMT_P_FLG]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_NO_CLC_ACV]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_NO_CLC_ACV]  DEFAULT (' ') FOR [NO_CLC_ACV]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_PA_TORT]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_PA_TORT]  DEFAULT (' ') FOR [PA_TORT]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_ST_TERIT_C'']') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_ST_TERIT_C']  DEFAULT ('') FOR [ST_TERIT_C]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_BROKER_COD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_BROKER_COD]  DEFAULT (' ') FOR [BROKER_COD]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_DIR_BILL]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_DIR_BILL]  DEFAULT (' ') FOR [DIR_BILL]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_DRVS_BDAY]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_DRVS_BDAY]  DEFAULT (' ') FOR [DRVS_BDAY]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_DRVS_ST_LC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_DRVS_ST_LC]  DEFAULT (' ') FOR [DRVS_ST_LC]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_UpdateDate]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_UpdateDate]  DEFAULT (getdate()) FOR [UpdateDate]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_PHLINS]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_PHLINS]  DEFAULT (' ') FOR [PHLINS]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_DRVGENDER]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_DRVGENDER]  DEFAULT (' ') FOR [DRVGENDER]
END

GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DF_Arch_GRUNDY_Policy_TRANSDATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Arch_GRUNDY_Policy] ADD  CONSTRAINT [DF_Arch_GRUNDY_Policy_TRANSDATE]  DEFAULT (' ') FOR [TRANSDATE]
END

GO
