IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACA_ERRORS]') AND type in (N'U'))
DROP TABLE [dbo].[ACA_ERRORS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACA_ERRORS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ACA_ERRORS](
	[ACA_ID] [int] NOT NULL,
	[ERROR_ID] [int] NOT NULL
) ON [PRIMARY]
END
GO
