IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FPT15868_TMP_Arch_GRUNDY_Policy]') AND type in (N'U'))
DROP TABLE [dbo].[FPT15868_TMP_Arch_GRUNDY_Policy]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FPT15868_TMP_Arch_GRUNDY_Policy]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[FPT15868_TMP_Arch_GRUNDY_Policy](
	[Arch_GRUNDY_Policy_ID] [int] NOT NULL,
	[REC_NUM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_NUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUB_AGENT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCEPT_DATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXP_DATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME_INSURED] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRESS_N] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY_NAME] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_CD] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_FORM_01] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_FORM_02] [nvarchar](52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP_CODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BROKER] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BADDRESS] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BCITY_NAME] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTATE_CD] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BZIP_CODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOD_INS_EP] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOD_INS_EO] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MED_PAY_EP] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNINS_MTR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDTL_COV] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_1] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_1] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_1] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_2] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_2] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_2] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_3] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_3] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_3] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACV_4] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_L_DED_4] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLL_L_DED_4] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOW_LABOR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR_1] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE1] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM1] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR_2] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE2] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM2] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR_3] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE3] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE3] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM3] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_YEAR4] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAKE4] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE4] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIN_SER_NUM4] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO1] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO2] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO3] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GARAGE_LO4] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_1] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_1b] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_2] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_2B] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_3] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_3B] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_4] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSS_PAY_4b] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISSUE_DATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST_SUR_CHG] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOT_VEHCLS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENDORSEMNT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREM_TERM] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_COM_LD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_COL_LD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_P_ADJ] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TERM_E_PRE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TTL_TERM_P] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ID_CDS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEW_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REINST_FEE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMM_ACCT_NUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRINT_FLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXEMPT_50] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEH_EFF_DT] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DR_LIC_NUM] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOT_ACV] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPEC_R_COL] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPEC_R_CMP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_FLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_CODE] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REMT_P_FLG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NO_CLC_ACV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PA_TORT] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ST_TERIT_C] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BROKER_COD] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIR_BILL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRVS_BDAY] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRVS_ST_LC] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordStatus] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UpdateDate] [datetime] NULL,
	[PHLINS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRVGENDER] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANSDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
