IF  EXISTS (SELECT * FROM sys.schemas WHERE name = N'PHLYSQL1')
DROP SCHEMA [PHLYSQL1]
GO
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'PHLYSQL1')
EXEC sys.sp_executesql N'CREATE SCHEMA [PHLYSQL1]'

GO
