IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[POLGEN_Product_Info]') AND type in (N'U'))
DROP TABLE [dbo].[POLGEN_Product_Info]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[POLGEN_Product_Info]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[POLGEN_Product_Info](
	[Product_Info_ID] [int] IDENTITY(1,1) NOT NULL,
	[Product_Info_Desc] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Product_Code] [char](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_Company_Info] PRIMARY KEY CLUSTERED 
(
	[Product_Info_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[POLGEN_Product_Info]') AND name = N'IX_POLGEN_Product_Info')
CREATE UNIQUE NONCLUSTERED INDEX [IX_POLGEN_Product_Info] ON [dbo].[POLGEN_Product_Info]
(
	[Product_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
