IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'PHLYNT\APPS DEVELOPMENT TEAM')
DROP USER [PHLYNT\APPS DEVELOPMENT TEAM]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'PHLYNT\APPS DEVELOPMENT TEAM')
CREATE USER [PHLYNT\APPS DEVELOPMENT TEAM] FOR LOGIN [PHLYNT\APPS DEVELOPMENT TEAM]
GO
sys.sp_addrolemember @rolename = N'db_owner', @membername = N'PHLYNT\APPS DEVELOPMENT TEAM'
GO
