IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[State_NY_All_Lines_View_1]'))
DROP VIEW [dbo].[State_NY_All_Lines_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[State_NY_All_Lines_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.State_NY_All_Lines_View_1
AS
SELECT     dbo.ALL_POLICIES_12_premium_summary_December.statecode, dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_December.productcode, dbo.ALL_POLICIES_12_premium_summary_December.Fiscal_AY_Year, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.currentwrittenpremium) AS currentwrittenpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.currentearnedpremium) AS currentearnedpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Policy_count_Reporting_Coverage) AS Policy_count_Reporting_Coverage, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Incurred_Loss_ALAE_with_SS_NonCat) AS Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Capped_Incurred_Loss_ALAE_with_SS_wo_cat) AS Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat) AS Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, SUM(dbo.ALL_POLICIES_12_premium_summary_December.Reported_Claims) AS Reported_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Malpractice_Count) AS COL_GLBI_Malpractice_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Malpractice_Loss) AS COL_GLBI_Malpractice_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Fraud_Breach_of_Contract_Count) AS COL_GLBI_Fraud_Breach_of_Contract_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Fraud_Breach_of_Contract_Loss) AS COL_GLBI_Fraud_Breach_of_Contract_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Injury_Count) AS COL_GLBI_Injury_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Injury_Loss) AS COL_GLBI_Injury_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Other_Count) AS COL_GLBI_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Other_Loss) AS COL_GLBI_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Sexual_Assault_Molest_Abuse_Count) AS COL_GLBI_Sexual_Assault_Molest_Abuse_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Sexual_Assault_Molest_Abuse_Loss) AS COL_GLBI_Sexual_Assault_Molest_Abuse_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_PropertyDamage_Loss) AS COL_GLBI_PropertyDamage_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_PropertyDamage_Count) AS COL_GLBI_PropertyDamage_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Theft_Loss) AS COL_GLBI_Theft_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Theft_Count) AS COL_GLBI_Theft_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_SlanderDefamtion_Loss) AS COL_GLBI_SlanderDefamtion_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_SlanderDefamtion_Count) AS COL_GLBI_SlanderDefamtion_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Discrim_WrongfulTermination_Loss) AS COL_GLBI_Discrim_WrongfulTermination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_GLBI_Discrim_WrongfulTermination_Count) AS COL_GLBI_Discrim_WrongfulTermination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Incurred_Claims) AS Incurred_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Commission_dollars) AS Commission_dollars, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Commission_Premiums) AS Commission_Premiums, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.Price_Monitor_Standard_CovGrp_GL_Monitored_range, 
                      dbo.Policy_Information_ALL_POLICIES_December.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_December.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_December.Branch_Region, dbo.Policy_Information_ALL_POLICIES_December.program, 
                      dbo.Policy_Information_ALL_POLICIES_December.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_December.product_group, dbo.Policy_Information_ALL_POLICIES_December.Primary_Umbrella, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Earned_Buildings) AS Earned_Buildings, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Earned_Locations) AS Earned_Locations, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Earned_TIV) AS Earned_TIV, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_December.Primary_Producer, SUM(dbo.ALL_POLICIES_12_premium_summary_December.Policy_count_All_Cov_Combined) 
                      AS Policy_count_All_Cov_Combined, dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_Working_Cover_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Policy_count_Coverage_Group) AS Policy_count_Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_December.accountnumber, dbo.Policy_Information_ALL_POLICIES_December.Primary_Producer_type, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Playground_YN, dbo.Policy_Information_Underwriting_Check_List_December.Playground_Equip_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Pool_YN, dbo.Policy_Information_Underwriting_Check_List_December.Sports_Activities_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Tennis_Bubble_YN, dbo.Policy_Information_Underwriting_Check_List_December.Tennis_Courts_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Number_of_Swimming_Pools_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Incurred_Loss_ALAE_with_SS) AS Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Capped_Incurred_Loss_ALAE_with_SS) AS Capped_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Ult_LDF_Incurred_Loss_ALAE_with_SS) AS Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS) AS Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.GL_Aggregate_Limit, dbo.Policy_Information_ALL_POLICIES_GL_December.GL_Deductible, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.GLDX_Indicator, dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_Form, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_OCC_Limit, dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_Agg_Limit, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_Form_Group, dbo.Policy_Information_ALL_POLICIES_GL_December.GL_Occurrence_Limit, 
                      dbo.Policy_Information_ALL_POLICIES_December.Endorsement_GLDX_YN, dbo.ALL_POLICIES_12_premium_summary_December.policynumber, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.Property_Coverage_Form, dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Form, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Constr_Code_Dominant_NAME, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Hail_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.ZIP_Pop_Density_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Avg_Bld_Rate_Range, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Avg_Bld_Rate_rd2, dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Deductible, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Wind_Hail_Count) AS COL_Prop_Wind_Hail_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Wind_Hail_Loss) AS COL_Prop_Wind_Hail_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Water_Other_Loss) AS COL_Prop_Water_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Water_Other_Count) AS COL_Prop_Water_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Water_Sprinkler_Loss) AS COL_Prop_Water_Sprinkler_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Water_Sprinkler_Count) AS COL_Prop_Water_Sprinkler_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Theft_Van_Loss) AS COL_Prop_Theft_Van_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Theft_Van_Count) AS COL_Prop_Theft_Van_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Fire_Lightning_Explosion_Loss) AS COL_Prop_Fire_Lightning_Explosion_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Fire_Lightning_Explosion_Count) AS COL_Prop_Fire_Lightning_Explosion_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Other_Loss) AS COL_Prop_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.COL_Prop_Other_Count) AS COL_Prop_Other_Count, 
                      dbo.Policy_Information_ALL_POLICIES_December.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_December.Account_Name, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_December.Incurred_Loss_ALAE_with_SS_CatOnly) AS Incurred_Loss_ALAE_with_SS_CatOnly, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Total_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Truck_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_PPT_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Buses_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_VanPools_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_OtherPublic_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Other_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Dual_Control_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Dual_Control_Percent_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Hired_Auto, dbo.Policy_Information_ALL_POLICIES_AUTO_December.Non_Owned_Auto, 
                      dbo.Policy_Information_GL_AVG_RATES_December.Churches_Avg_Rate_Range, dbo.Policy_Information_GL_AVG_RATES_December.Day_Care_Avg_Rate_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Primary_Producer_code, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_NonCat_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_NonCat_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_NonCat_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_Working_Cover_Range, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      AccessPHLYEOM.dbo.Division.DivisionName, AccessPHLYEOM.dbo.product.producttype, 
                      dbo.ALL_POLICIES_12_premium_summary_December.Fiscal_AY_Month_Ending, dbo.ALL_POLICIES_12_premium_summary_December.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_December.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_December.PIC_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_December.First_Policy_Year, dbo.Policy_Information_ALL_POLICIES_December.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_December.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_December.Source_Detail_Name, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Territory_Dominant, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Territory_Dominant_percent, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Dom_Terr_description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Dom_Region_in_State
FROM         dbo.ALL_POLICIES_12_premium_summary_December LEFT OUTER JOIN
                      AccessPHLYEOM.dbo.product ON dbo.ALL_POLICIES_12_premium_summary_December.productcode = AccessPHLYEOM.dbo.product.productcode LEFT OUTER JOIN
                      AccessPHLYEOM.dbo.Division ON AccessPHLYEOM.dbo.product.DivisionID = AccessPHLYEOM.dbo.Division.DivisionID LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Information_ALL_POLICIES_AUTO_December.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_Underwriting_Check_List_December ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Information_Underwriting_Check_List_December.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_GL_AVG_RATES_December ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Information_GL_AVG_RATES_December.Policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_GL_December ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Information_ALL_POLICIES_GL_December.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Information_ALL_POLICIES_FireAllied_December.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_December ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Information_ALL_POLICIES_December.policynumber LEFT OUTER JOIN
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY ON 
                      dbo.ALL_POLICIES_12_premium_summary_December.policynumber = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.policynumber AND
                       dbo.ALL_POLICIES_12_premium_summary_December.productcode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.Productcode AND
                       dbo.ALL_POLICIES_12_premium_summary_December.statecode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.statecode AND 
                      dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Group = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.coverage_group
GROUP BY dbo.ALL_POLICIES_12_premium_summary_December.statecode, dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_December.productcode, dbo.ALL_POLICIES_12_premium_summary_December.Fiscal_AY_Year, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.Price_Monitor_Standard_CovGrp_GL_Monitored_range, 
                      dbo.Policy_Information_ALL_POLICIES_December.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_December.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_December.Branch_Region, dbo.Policy_Information_ALL_POLICIES_December.program, 
                      dbo.Policy_Information_ALL_POLICIES_December.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_December.product_group, dbo.Policy_Information_ALL_POLICIES_December.Primary_Umbrella, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_December.Primary_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.accountnumber, dbo.Policy_Information_ALL_POLICIES_December.Primary_Producer_type, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Playground_YN, dbo.Policy_Information_Underwriting_Check_List_December.Playground_Equip_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Pool_YN, dbo.Policy_Information_Underwriting_Check_List_December.Sports_Activities_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Tennis_Bubble_YN, dbo.Policy_Information_Underwriting_Check_List_December.Tennis_Courts_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_December.Number_of_Swimming_Pools_Range, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.GL_Aggregate_Limit, dbo.Policy_Information_ALL_POLICIES_GL_December.GL_Deductible, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.GLDX_Indicator, dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_Form, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_OCC_Limit, dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_Agg_Limit, 
                      dbo.Policy_Information_ALL_POLICIES_GL_December.SAM_Form_Group, dbo.Policy_Information_ALL_POLICIES_GL_December.GL_Occurrence_Limit, 
                      dbo.Policy_Information_ALL_POLICIES_December.Endorsement_GLDX_YN, dbo.ALL_POLICIES_12_premium_summary_December.policynumber, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.Property_Coverage_Form, dbo.ALL_POLICIES_12_premium_summary_December.Coverage_Form, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Constr_Code_Dominant_NAME, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Hail_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.ZIP_Pop_Density_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Avg_Bld_Rate_Range, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Avg_Bld_Rate_rd2, dbo.Policy_Information_ALL_POLICIES_FireAllied_December.FA_Deductible, 
                      dbo.Policy_Information_ALL_POLICIES_December.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_December.Account_Name, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Total_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Truck_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_PPT_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Buses_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_VanPools_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_OtherPublic_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Other_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Dual_Control_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Auto_Vehicle_count_Dual_Control_Percent_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_December.Hired_Auto, dbo.Policy_Information_ALL_POLICIES_AUTO_December.Non_Owned_Auto, 
                      dbo.Policy_Information_GL_AVG_RATES_December.Churches_Avg_Rate_Range, dbo.Policy_Information_GL_AVG_RATES_December.Day_Care_Avg_Rate_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Primary_Producer_code, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_NonCat_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_Working_Cover_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_NonCat_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_UltLoss_Ratio_NonCat_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_December.Account_RepLoss_Ratio_NonCat_Working_Cover_Range, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      AccessPHLYEOM.dbo.Division.DivisionName, AccessPHLYEOM.dbo.product.producttype, 
                      dbo.ALL_POLICIES_12_premium_summary_December.Fiscal_AY_Month_Ending, dbo.ALL_POLICIES_12_premium_summary_December.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_December.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_December.PIC_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_December.First_Policy_Year, dbo.Policy_Information_ALL_POLICIES_December.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_December.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_December.Source_Detail_Name, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Territory_Dominant, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Territory_Dominant_percent, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Dom_Terr_description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_December_test_NY.AL_Dom_Region_in_State
HAVING      (dbo.ALL_POLICIES_12_premium_summary_December.statecode = ''NY'') AND (dbo.ALL_POLICIES_12_premium_summary_December.Fiscal_AY_Year > 2007)
' 
GO
