IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Policy_Information_VS1]') AND type in (N'U'))
DROP TABLE [dbo].[Policy_Information_VS1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Policy_Information_VS1]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Policy_Information_VS1](
	[accountnumber] [int] NULL,
	[policynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policyeffectivedate] [datetime] NULL,
	[productcode] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[acctngyear] [int] NULL,
	[billplanshortdesc] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Product_Group] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Package_Monoline] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policy_effective_year] [int] NULL,
	[policy_effective_month] [int] NULL,
	[Prior_Policy_Number] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Tail] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branchcode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Office] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Region] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Renewals] [int] NULL,
	[zipcode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAICS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Division] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Major_group] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Industry_Group] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Completed_Signed_Application] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Completed_ACORD] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Brochures] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Supplemental_Claim_Form_Loss_Run] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Completed_Supplemental_Apps] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Signed_Statement_of_Values] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Website_Address] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Abuse_Molestation] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Asbestos_Lead] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Athletic_Participants] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Buildings_Greater_than_3_Stories] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coastal_Wind_Guides] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Life_Safety_Requirements] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Martial_Arts] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Locations_Y_N] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Special_Events] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Pool] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UM_UIM_State_Issues] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Volunteers] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Umbrella] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diving_Boards] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Non_Owned_Exposure] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Builders_Risk] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hail_Exposure] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hired_Exposure] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Limits_ITV] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mold_Exposure] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIIC_Boiler] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Stadiums] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Loss_Control_Requests] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Rated_Premium_Agrees_With_Binding_Premium] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Auto_Facultative_Reinsurance_Bound] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Binding_Requirements_Fulfilled] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIIC_Boiler_2] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Within_Underwriting_Authority] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Referred_to_Management] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Facultative_Reinsurance_Required] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Blanket] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Locations_Facultative_is_Required] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[No_Loss_Letter_Received] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[No_Prior_Coverage] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Corporal_Pun_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Pub_PreHS_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Pub_HS_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Trade_Voc_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Priv_PreHS_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Priv_HS_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Priv_PreHS_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Priv_HS_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_DayCare_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_DayCare_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Camps_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Camps_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Univ_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Schools_Univ_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Dorms_OTNFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Dorms_NFP_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Auto_Driver_Training_Programs_Educational_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Auto_Driver_Training_Programs_Commercial_Y_N] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Business_Name] [char](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Charter_School] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
