IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Latest_Policy_Information_GL_AVG_RATES_RangesOnly_View_1_table]') AND type in (N'U'))
DROP TABLE [dbo].[Latest_Policy_Information_GL_AVG_RATES_RangesOnly_View_1_table]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Latest_Policy_Information_GL_AVG_RATES_RangesOnly_View_1_table]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Latest_Policy_Information_GL_AVG_RATES_RangesOnly_View_1_table](
	[Policynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amusement_Centers_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amusement_Centers_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amusement_Parks_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amusement_Parks_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Apartments_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Apartments_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Apartments_Garden_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Apartments_Garden_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Apt_Outside_NY_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Apt_Outside_NY_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Athletic_Programs_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Athletic_Programs_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Bank_Office_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Bank_Office_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Bank_Office_SelfMtd_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Bank_Office_SelfMtd_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Boarding_Rooming_House_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Boarding_Rooming_House_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Camps_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Churches_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Churches_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Clubs_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Clubs_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[College_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[College_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[College_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[College_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[College_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[College_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Concessionaires_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Concessionaires_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Condo_Association_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Condo_Association_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Corp_Punishment_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Corp_Punishment_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Day_Care_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Day_Care_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Day_Care_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Day_Care_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Day_Care_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Day_Care_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dormitories_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Driving_Range_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Driving_Range_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dwellings_Single_Fam_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dwellings_Single_Fam_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Exhibition_Bldgs_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Exhibition_Bldgs_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Exhibitions_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Exhibitions_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Golf_Municipal_Public_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Golf_Municipal_Public_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Golf_Club_Country_Club_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Golf_Club_Country_Club_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Guides_Outfitters_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Guides_Outfitters_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_AlcoholDrug_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_AlcoholDrug_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Homes_For_Aged_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Homes_For_Aged_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Homes_For_Aged_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Homes_For_Aged_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Phys_Handicap_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Phys_Handicap_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Phys_Handicap_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Phys_Handicap_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Psycopathic_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCF_Psycopathic_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Health_Exercise_Club_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Health_Exercise_Club_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HomeHealthCare_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HomeHealthCare_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HomeHealthCareNonSales_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HomeHealthCareNonSales_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HomeHealthCareSales_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HomeHealthCareSales_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Homeowner_Assoc_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Homeowner_Assoc_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_w_PB_GE4_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_w_PB_GE4_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_w_PB_LT4_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_w_PB_LT4_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_wo_PB_GE4_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_wo_PB_GE4_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_wo_PB_LT4_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HT_wo_PB_LT4_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hotels_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hotels_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Indoor_play_centers_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Indoor_play_centers_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Janitorial_Services_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Janitorial_Services_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Lakes_Resevoirs_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Lakes_Resevoirs_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Miniature_Golf_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Miniature_Golf_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mobile_Home_Parks_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mobile_Home_Parks_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Offices_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Offices_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Offices_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Offices_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Outpatient_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Outpatient_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Parks_Playgrounds_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Parks_Playgrounds_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_HS_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_HS_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Parking_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Parking_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Pre_HS_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Pre_HS_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Pre_HS_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Pre_HS_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Schools_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Schools_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Schools_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Private_Schools_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Public_Schools_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Public_Schools_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Public_Schools_HS_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Public_Schools_HS_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Public_Schools_Pre_HS_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Public_Schools_Pre_HS_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Race_Tracks_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Race_Tracks_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sales_Service_Orgs_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sales_Service_Orgs_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Schools_FP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Schools_FP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Schools_NP_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Schools_NP_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Shelter_Mission_HlfwHouse_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Shelter_Mission_HlfwHouse_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Skating_Rinks_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Skating_Rinks_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Stadiums_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Stadiums_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Swimming_Pools_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Swimming_Pools_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vocational_Schools_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vocational_Schools_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YMCA_YWCA_Class_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YMCA_YWCA_Avg_Rate_Range] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Expr1] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Latest_Policy_Information_GL_AVG_RATES_RangesOnly_View_1_table]') AND name = N'IX_policynumber')
CREATE NONCLUSTERED INDEX [IX_policynumber] ON [dbo].[Latest_Policy_Information_GL_AVG_RATES_RangesOnly_View_1_table]
(
	[Policynumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
