IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NPDO_Museums]') AND type in (N'U'))
DROP TABLE [dbo].[NPDO_Museums]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NPDO_Museums]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[NPDO_Museums](
	[accountnumber] [int] NULL,
	[policynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policyeffectivedate] [datetime] NULL,
	[statecode] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coverage_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coverage_Reporting_group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coverage_Form] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[productcode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[experienceproduct] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fiscal_AY_Month_Ending] [int] NULL,
	[Fiscal_AY_Year] [int] NULL,
	[acctngyear] [int] NULL,
	[Last_Reporting_Year] [int] NULL,
	[Last_Reporting_Month] [int] NULL,
	[currentwrittenpremium] [decimal](15, 2) NULL,
	[currentearnedpremium] [decimal](15, 2) NULL,
	[Policy_count_All_Cov_Combined] [float] NULL,
	[Policy_count_Reporting_Coverage] [float] NULL,
	[Policy_count_Coverage_Group] [float] NULL,
	[Loss_Evaluation_Month] [int] NULL,
	[Loss_Evaluation_Year] [int] NULL,
	[Loss_ALAE_Cap] [float] NULL,
	[COL_Breach_of_Contract_Count] [decimal](15, 2) NULL,
	[COL_Breach_of_Contract_Loss] [decimal](15, 2) NULL,
	[COL_Discrimination_Count] [decimal](15, 2) NULL,
	[COL_Discrimination_Loss] [decimal](15, 2) NULL,
	[COL_Wrongful_Termination_Count] [decimal](15, 2) NULL,
	[COL_Wrongful_Termination_Loss] [decimal](15, 2) NULL,
	[COL_Harrassment_Count] [decimal](15, 2) NULL,
	[COL_Harrassment_Loss] [decimal](15, 2) NULL,
	[COL_DO_Other_Count] [decimal](15, 2) NULL,
	[COL_DO_Other_Loss] [decimal](15, 2) NULL,
	[COL_EPL_Other_Count] [decimal](15, 2) NULL,
	[COL_EPL_Other_Loss] [decimal](15, 2) NULL,
	[COL_Fiduciary_Other_Count] [decimal](15, 2) NULL,
	[COL_Fiduciary_Other_Loss] [decimal](15, 2) NULL,
	[COL_Worplace_Violence_Other_Count] [decimal](15, 2) NULL,
	[COL_Worplace_Violence_Other_Loss] [decimal](15, 2) NULL,
	[COL_Internet_Other_Count] [decimal](15, 2) NULL,
	[COL_Internet_Other_Loss] [decimal](15, 2) NULL,
	[COL_SLD_All_Other_Count] [decimal](15, 2) NULL,
	[COL_SLD_All_Other_Loss] [decimal](15, 2) NULL,
	[COL_AE_Breach_of_Contract_Count] [decimal](15, 2) NULL,
	[COL_AE_Breach_of_Contract_Loss] [decimal](15, 2) NULL,
	[COL_AE_Breach_of_Fiduciary_Liability_Count] [decimal](15, 2) NULL,
	[COL_AE_Breach_of_Fiduciary_Liability_Loss] [decimal](15, 2) NULL,
	[COL_AE_Financial_Advisor_Count] [decimal](15, 2) NULL,
	[COL_AE_Financial_Advisor_Loss] [decimal](15, 2) NULL,
	[COL_AE_Misconduct_Count] [decimal](15, 2) NULL,
	[COL_AE_Misconduct_Loss] [decimal](15, 2) NULL,
	[COL_AE_Wills_Estate_Count] [decimal](15, 2) NULL,
	[COL_AE_Wills_Estate_Loss] [decimal](15, 2) NULL,
	[COL_AE_Corporate_Count] [decimal](15, 2) NULL,
	[COL_AE_Corporate_Loss] [decimal](15, 2) NULL,
	[COL_AE_Tax_Liability_Count] [decimal](15, 2) NULL,
	[COL_AE_Tax_Liability_Loss] [decimal](15, 2) NULL,
	[COL_AE_Violation_GAAP_Count] [decimal](15, 2) NULL,
	[COL_AE_Violation_GAAP_Loss] [decimal](15, 2) NULL,
	[COL_AE_All_Other_Count] [decimal](15, 2) NULL,
	[COL_AE_All_Other_Loss] [decimal](15, 2) NULL,
	[COL_CL_Breach_of_Contract_Count] [decimal](15, 2) NULL,
	[COL_CL_Breach_of_Contract_Loss] [decimal](15, 2) NULL,
	[COL_CL_Breach_of_Fiduciary_Liability_Count] [decimal](15, 2) NULL,
	[COL_CL_Breach_of_Fiduciary_Liability_Loss] [decimal](15, 2) NULL,
	[COL_CL_Financial_Advisor_Count] [decimal](15, 2) NULL,
	[COL_CL_Financial_Advisor_Loss] [decimal](15, 2) NULL,
	[COL_CL_Misconduct_Count] [decimal](15, 2) NULL,
	[COL_CL_Misconduct_Loss] [decimal](15, 2) NULL,
	[COL_CL_Wills_Estate_Count] [decimal](15, 2) NULL,
	[COL_CL_Wills_Estate_Loss] [decimal](15, 2) NULL,
	[COL_CL_Corporate_Count] [decimal](15, 2) NULL,
	[COL_CL_Corporate_Loss] [decimal](15, 2) NULL,
	[COL_CL_Tax_Liability_Count] [decimal](15, 2) NULL,
	[COL_CL_Tax_Liability_Loss] [decimal](15, 2) NULL,
	[COL_CL_Violation_GAAP_Count] [decimal](15, 2) NULL,
	[COL_CL_Violation_GAAP_Loss] [decimal](15, 2) NULL,
	[COL_CL_Negligent_Training_Count] [decimal](15, 2) NULL,
	[COL_CL_Negligent_Training_Loss] [decimal](15, 2) NULL,
	[COL_CL_Electronic_Data_Damage_Count] [decimal](15, 2) NULL,
	[COL_CL_Electronic_Data_Damage_Loss] [decimal](15, 2) NULL,
	[COL_CL_All_Other_Count] [decimal](15, 2) NULL,
	[COL_CL_All_Other_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Malpractice_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Malpractice_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Fraud_Breach_of_Contract_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Fraud_Breach_of_Contract_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Injury_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Injury_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Other_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Other_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Sexual_Assault_Molest_Abuse_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Sexual_Assault_Molest_Abuse_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_PropertyDamage_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_PropertyDamage_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Theft_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Theft_Count] [decimal](15, 2) NULL,
	[COL_GLBI_SlanderDefamtion_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_SlanderDefamtion_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Discrim_WrongfulTermination_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Discrim_WrongfulTermination_Count] [decimal](15, 2) NULL,
	[COL_Prop_Fire_Lightning_Explosion_Count] [decimal](15, 2) NULL,
	[COL_Prop_Fire_Lightning_Explosion_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Theft_Van_Count] [decimal](15, 2) NULL,
	[COL_Prop_Theft_Van_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Water_Sprinkler_Count] [decimal](15, 2) NULL,
	[COL_Prop_Water_Sprinkler_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Water_Other_Count] [decimal](15, 2) NULL,
	[COL_Prop_Water_Other_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Wind_Hail_Count] [decimal](15, 2) NULL,
	[COL_Prop_Wind_Hail_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Other_Count] [decimal](15, 2) NULL,
	[COL_Prop_Other_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_AllOther_Count] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_AllOther_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_PropDam_Count] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_PropDam_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Coll_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Coll_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Glass_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Glass_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Other_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Other_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Theft_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Theft_Loss] [decimal](15, 2) NULL,
	[Case_Loss] [decimal](15, 2) NULL,
	[Case_ALAE] [decimal](15, 2) NULL,
	[Paid_Loss] [decimal](15, 2) NULL,
	[Paid_ALAE] [decimal](15, 2) NULL,
	[Sal_Subro] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_with_SS_CatOnly] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_without_SS_NonCat] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_without_SS_CatOnly] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_with_SS_NonCat] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_without_SS] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Capped_Incurred_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Capped_Incurred_Loss_ALAE_with_SS_wo_cat] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_with_SS_CatOnly] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_without_SS] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_without_SS_CatOnly] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_without_SS_NonCat] [decimal](15, 2) NULL,
	[Ult_LDF_Capped_Inc_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat] [decimal](15, 2) NULL,
	[Reported_Claims] [decimal](15, 2) NULL,
	[Open_Claims] [decimal](15, 2) NULL,
	[Closed_With_Pay_Claims] [decimal](15, 2) NULL,
	[Closed_Without_Pay_Claims] [decimal](15, 2) NULL,
	[Experience_Product_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Renewals] [int] NULL,
	[Renewals_Range] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[underwriterPID] [int] NULL,
	[Idnum] [int] NULL,
	[Companycode] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policyid] [int] NULL,
	[billplancode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[product_group] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[package_monoline] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policy_effective_year] [int] NULL,
	[policy_effective_month] [int] NULL,
	[policyexpirationdate] [datetime] NULL,
	[Prior_Policy_number] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Tail] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branchcode] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Renew_New_Auto] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[First_Policy_Year_Temp] [datetime] NULL,
	[Latest_PY] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[First_Policy_Year] [varchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[written_premium_policy] [float] NULL,
	[underwriter] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillplanshortDesc] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Office] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Region] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[zipcode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAICS] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Program_Code] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Business_Name] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Business_Desc] [char](72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County] [nvarchar](511) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County_Pop_Density] [float] NULL,
	[program] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Written_Premium_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County_Pop_Density_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIC_Producer_code] [int] NULL,
	[PIC_Commission_pct] [float] NULL,
	[Primary_Producer_code] [int] NULL,
	[Primary_Commission_pct] [float] NULL,
	[PIC_Producer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIC_Producer_type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Primary_Producer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Primary_Producer_type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Commission_pct] [float] NULL,
	[Commission_dollars] [float] NULL,
	[Commission_Premiums] [float] NULL,
	[Count_of_Account_Numbers] [float] NULL,
	[Count_of_Account_Numbers_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Renewal_Curr_MIPS_WP] [decimal](38, 2) NULL,
	[Renewal_calc_RateChangePrem_onExpiringTermPrem] [float] NULL,
	[Prior_MIPS_PolTerm_WP] [float] NULL,
	[Standard_Curr_MIPS_WP] [decimal](38, 2) NULL,
	[Standard_Premium_Curr] [float] NULL,
	[Benchmark_Curr_MIPS_WP] [decimal](38, 2) NULL,
	[Benchmark_NormPrem] [float] NULL,
	[Benchmark_Curr_Exposure] [float] NULL,
	[Price_Monitor_Renewal_Portion_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Portion_of_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Portion_of_CovGrp_St_Class_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_CovGrp_St_Class_Monitored] [float] NULL,
	[Price_Monitor_Standard_Portion_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Standard_Changes_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Standard_Portion_of_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Standard_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Benchmark_Rate] [float] NULL,
	[Price_Monitor_Benchmark_CW_for_Class] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_CovGrp_St_Class_Monitored_range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Price_Monitor_Standard_Cov_Grp_Monitored_range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Price_Monitor_Benchmark_Rate_to_CW_range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DF_Limit] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DF_Base_Retention] [float] NULL,
	[DF_Alt_Retention] [float] NULL,
	[DF_RatingClass] [int] NULL,
	[DO_Limit] [float] NULL,
	[DO_Base_Retention] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DO_Alt_Retention] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DO_RatingClass] [int] NULL,
	[DO_Revenues] [float] NULL,
	[EPL_Limit] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPL_Base_Retention] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPL_Alt_Retention] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPL_RatingClass] [int] NULL,
	[EPL_Num_of_Employees] [int] NULL,
	[Business_Type] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPL_Num_of_Employees_Range] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DO_Revenues_range] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Trade_Assoc] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TrimBusiness_Type] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Financials] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Supplemental_Claim_Form_Loss_Run] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Bylaws] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[List_of_DOs] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Employment_App] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Employment_Handbook] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Form_5500] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Website_Info_Only] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Website_Transactional_eCommerce] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[No_of_years_in_Operation] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Tax_Exempt] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Publish_Mag_Per_News] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Prod_Research_Devel_Test_Certif_Services] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Discip_Action_Result_of_Peer_Rev_Act] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Administer_Ins_Progr_for_Members] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Positive_Fund_Balance] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Subsidiaries_Affiliates] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Discipl_Admin_Criminal_Action] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Merger_Acquisition] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Member_Certif_Services] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Peer_Review_Act_or_Disipl_Actions] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Full_Time_Employees] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Part_Time_Employees] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Temporary_Employees] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Lease_Employees] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Turnover_Rate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Employment_Application_Handbook] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Plan_Assets] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_Participants] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Proper_empl_procedures_in_place] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Security_precautions_taken] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Information_Only] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Transaction_eCommerce] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[No_Loss_Letter_Received] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[No_Prior_Coverage] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Clean_Warranty_Letter_Received] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Supplemental_Claim_Form_Received] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Full_Time_Employees_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Part_Time_Employees_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Temporary_Employees_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Lease_Employees_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Turnover_Rate_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Plan_Assets_Range] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_Participants_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Revenue_Gross_Billing_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[No_of_years_in_Operation_Range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
