IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Policy_Information_ALL_POLICIES_Target_201102]') AND type in (N'U'))
DROP TABLE [dbo].[Policy_Information_ALL_POLICIES_Target_201102]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Policy_Information_ALL_POLICIES_Target_201102]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Policy_Information_ALL_POLICIES_Target_201102](
	[accountnumber] [int] NULL,
	[Policynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_Name] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insured_Name] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Productcode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProductType] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DivisionName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Region] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIC_Producer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Primary_Producer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[underwriter] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyEntityState] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policyEffectivedate] [datetime] NULL,
	[policyexpirationdate] [datetime] NULL,
	[policy_effective_year] [int] NULL,
	[Last_Reporting_Year] [int] NULL,
	[Last_Reporting_Month] [int] NULL,
	[Renew_New_Auto] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Number_of_Renewals] [int] NULL,
	[Prior_Policy_number] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_2] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_3] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_4] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_5] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Automatic_Prior_Policy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Automatic_Prior_Policy_2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Automatic_Prior_Policy_3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Automatic_Prior_Policy_4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Automatic_Prior_Policy_5] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[written_premium_policy] [float] NULL,
	[Account_RepLoss_Ratio_NonCat_priorpolperiods_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_RepLoss_Ratio_NonCat] [float] NULL,
	[AutoRen_Written_Premium_Range] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AutoRen_Consecutive_Prior_AutoRenewals] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_Loss_Ratio_CurrentPolicy_and_4PriorRenewals_100DaysPreExpDate] [float] NULL,
	[AutoRen_Loss_Ratio_5PriorRenewals_45DaysPreEffDate] [float] NULL,
	[Incurred_Claims_3YrsPrior_90DaysPreEffDate] [float] NULL,
	[Open_claims_3YrsPrior_90DaysPreEffDate] [float] NULL,
	[Loss_Ratio_5PriorRenewals_45DaysPreEffDate] [float] NULL,
	[Last_Reporting_Date] [datetime] NULL,
	[Inforce_Policy_Indicator] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_Loss_Ratio_5PriorRenewals_45DaysPreEffDate] [float] NULL,
	[Automatic_CLD_Index_1_201102] [int] NULL,
	[Automatic_CLD_Index_2_201102] [int] NULL,
	[Automatic_CLD_Index_3_201102] [int] NULL,
	[Automatic_CLD_Index_4_201102] [int] NULL,
	[Automatic_CLD_Index_5_201102] [int] NULL,
	[Automatic_CLD_Index_6_201102] [int] NULL,
	[Automatic_CLD_Index_7_201102] [int] NULL,
	[Automatic_CLD_Index_8_201102] [int] NULL,
	[Automatic_CLD_Index_201102] [int] NULL,
	[Automatic_CLD_Written_Premium_Threshold_201102] [float] NULL,
	[Automatic_CLD_Account_Reported_Loss_Ratio_201102] [float] NULL,
	[Automatic_CLD_Applies_First_Renewal_201102] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Automatic_Qualifies_201102] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIC_Producer_code] [int] NULL,
	[Primary_Producer_code] [int] NULL,
	[Program_Code] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Automatic_SLD_Index_1_201102] [int] NULL,
	[Automatic_SLD_Index_2_201102] [int] NULL,
	[Automatic_SLD_Index_3_201102] [int] NULL,
	[Automatic_SLD_Index_4_201102] [int] NULL,
	[Automatic_SLD_Index_5_201102] [int] NULL,
	[Automatic_SLD_Index_6_201102] [int] NULL,
	[Automatic_SLD_Index_7_201102] [int] NULL,
	[Automatic_SLD_Index_8_201102] [int] NULL,
	[Automatic_SLD_Index_9_201102] [int] NULL,
	[Automatic_SLD_Index_10_201102] [int] NULL,
	[Automatic_SLD_Index_11_201102] [int] NULL,
	[Automatic_SLD_Index_12_201102] [int] NULL,
	[Automatic_SLD_Index_13_201102] [int] NULL,
	[Automatic_SLD_Index_14_201102] [int] NULL,
	[Automatic_SLD_Index_15_201102] [int] NULL,
	[Automatic_SLD_Index_16_201102] [int] NULL,
	[Automatic_SLD_Index_201102] [int] NULL,
	[Automatic_SLD_Written_Premium_Threshold_201102] [float] NULL,
	[Automatic_SLD_Max_Years_for_Auto_Renewal_201102] [int] NULL,
	[Automatic_SLD_Incurred_Claims_Number_201102] [int] NULL,
	[Automatic_SLD_Incurred_Claims_for_Years_201102] [int] NULL,
	[Automatic_SLD_Highest_Occurrence_Limit_201102] [int] NULL,
	[Automatic_SLD_Max_Employees_201102] [int] NULL,
	[Automatic_SLD_Blocked_Producers_201102] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Program] [char](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Automatic_CLD_Max_Years_for_Auto_Renewal_201102] [int] NULL,
	[Target_Renewal] [float] NULL,
	[Target_Automatic] [float] NULL,
	[Target_Final] [float] NULL,
	[Target_Dollar] [float] NULL,
	[Account_Loss_Ratio_CurrentPolicy_and_4PriorRenewals_100DaysPreExpDate_range] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_Loss_Ratio_5PriorRenewals_45DaysPreEffDate_range] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Target_LossRatio_for_Evaluation] [float] NULL,
	[Target_LossRatio_for_Evaluation_Range] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Automatic_SLD_Limit_for_Evalution] [int] NULL,
	[Automatic_SLD_NumOfEmployees_for_Evalution] [int] NULL,
	[Automatic_SLD_BusinessType_for_Evalution] [char](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PriceMonitor_Max_Acct_Year] [int] NULL,
	[PriceMonitor_Max_Acct_MM] [int] NULL,
	[PriceMonitor_Policy_Premium] [float] NULL,
	[PriceMonitor_Monitored_Premium] [float] NULL,
	[PriceMonitor_Monitored_Change_Premium] [float] NULL,
	[PriceMonitor_Monitored_Change_Base_Premium] [float] NULL,
	[PriceMonitor_Monitored_Rate_Change] [float] NULL,
	[PriceMonitor_Max_Acct_YearMM] [int] NULL,
	[PriceMonitor_Monitored_YN] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Target_Final_with_PriceMonitorChanges] [float] NULL,
	[Target_Final_with_PriceMonitor_Dollar] [float] NULL,
	[Target_Final_with_PriceMonitorChanges_Source] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Target_RRHR_disposition] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Loss_Ratio_CurrentPolicy_and_4PriorRenewals_LatestEvaluationDate] [float] NULL,
	[Loss_Ratio_CurrentPolicy_and_4PriorRenewals_LatestEvaluationDate_range] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_Loss_Ratio_CurrentPolicy_and_4PriorRenewals_LatestEvaluationDate] [float] NULL,
	[Account_Loss_Ratio_CurrentPolicy_and_4PriorRenewals_LatestEvaluationDate_range] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PriceMonitor_Standard_Policy_Premium] [float] NULL,
	[PriceMonitor_Standard_Monitored_Premium_nonUC] [float] NULL,
	[PriceMonitor_Standard_Monitored_StardardPremium_nonUC] [float] NULL,
	[PriceMonitor_Standard_Monitored_Premium_UC] [float] NULL,
	[PriceMonitor_Standard_Monitored_StardardPremium_UC] [float] NULL
) ON [PRIMARY]
END
GO
