IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AH_premium_summary]') AND type in (N'U'))
DROP TABLE [dbo].[AH_premium_summary]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AH_premium_summary]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[AH_premium_summary](
	[accountnumber] [int] NULL,
	[policynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policyeffectivedate] [datetime] NULL,
	[statecode] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coverage_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coverage_Reporting_group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coverage_Form] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[productcode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[experienceproduct] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fiscal_AY_Month_Ending] [int] NULL,
	[Fiscal_AY_Year] [int] NULL,
	[acctngyear] [int] NULL,
	[Last_Reporting_Year] [int] NULL,
	[Last_Reporting_Month] [int] NULL,
	[currentwrittenpremium] [decimal](15, 2) NULL,
	[currentearnedpremium] [decimal](15, 2) NULL,
	[Policy_count_All_Cov_Combined] [float] NULL,
	[Policy_count_Reporting_Coverage] [float] NULL,
	[Policy_count_Coverage_Group] [float] NULL,
	[Loss_Evaluation_Month] [int] NULL,
	[Loss_Evaluation_Year] [int] NULL,
	[Loss_ALAE_Cap] [float] NULL,
	[COL_GLBI_Malpractice_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Malpractice_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Fraud_Breach_of_Contract_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Fraud_Breach_of_Contract_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Injury_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Injury_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Other_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Other_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Sexual_Assault_Molest_Abuse_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Sexual_Assault_Molest_Abuse_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_PropertyDamage_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_PropertyDamage_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Theft_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Theft_Count] [decimal](15, 2) NULL,
	[COL_GLBI_SlanderDefamtion_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_SlanderDefamtion_Count] [decimal](15, 2) NULL,
	[COL_GLBI_Discrim_WrongfulTermination_Loss] [decimal](15, 2) NULL,
	[COL_GLBI_Discrim_WrongfulTermination_Count] [decimal](15, 2) NULL,
	[COL_Prop_Fire_Lightning_Explosion_Count] [decimal](15, 2) NULL,
	[COL_Prop_Fire_Lightning_Explosion_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Theft_Van_Count] [decimal](15, 2) NULL,
	[COL_Prop_Theft_Van_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Water_Sprinkler_Count] [decimal](15, 2) NULL,
	[COL_Prop_Water_Sprinkler_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Water_Other_Count] [decimal](15, 2) NULL,
	[COL_Prop_Water_Other_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Wind_Hail_Count] [decimal](15, 2) NULL,
	[COL_Prop_Wind_Hail_Loss] [decimal](15, 2) NULL,
	[COL_Prop_Other_Count] [decimal](15, 2) NULL,
	[COL_Prop_Other_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_AllOther_Count] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_AllOther_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_PropDam_Count] [decimal](15, 2) NULL,
	[COL_AUTO_LIAB_PropDam_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Coll_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Coll_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Glass_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Glass_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Other_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Other_Loss] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Theft_Count] [decimal](15, 2) NULL,
	[COL_AUTO_PHYS_Theft_Loss] [decimal](15, 2) NULL,
	[Case_Loss] [decimal](15, 2) NULL,
	[Case_ALAE] [decimal](15, 2) NULL,
	[Paid_Loss] [decimal](15, 2) NULL,
	[Paid_ALAE] [decimal](15, 2) NULL,
	[Sal_Subro] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_with_SS_CatOnly] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_without_SS_NonCat] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_without_SS_CatOnly] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_with_SS_NonCat] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_without_SS] [decimal](15, 2) NULL,
	[Incurred_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Capped_Incurred_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Capped_Incurred_Loss_ALAE_with_SS_wo_cat] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_with_SS_CatOnly] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_without_SS] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_without_SS_CatOnly] [decimal](15, 2) NULL,
	[Ult_LDF_Incurred_Loss_ALAE_without_SS_NonCat] [decimal](15, 2) NULL,
	[Ult_LDF_Capped_Inc_Loss_ALAE_with_SS] [decimal](15, 2) NULL,
	[Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat] [decimal](15, 2) NULL,
	[Reported_Claims] [decimal](15, 2) NULL,
	[Open_Claims] [decimal](15, 2) NULL,
	[Closed_With_Pay_Claims] [decimal](15, 2) NULL,
	[Closed_Without_Pay_Claims] [decimal](15, 2) NULL,
	[Experience_Product_Group] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Renewals_Range] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[underwriterPID] [int] NULL,
	[Companycode] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policyid] [int] NULL,
	[billplancode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[product_group] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[package_monoline] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policy_effective_year] [int] NULL,
	[policy_effective_month] [int] NULL,
	[policyexpirationdate] [datetime] NULL,
	[reinstatementdate] [datetime] NULL,
	[canceldate] [datetime] NULL,
	[Prior_Policy_number] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[New_Renew_Tail] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branchcode] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Renew_New_Auto] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Term_factor] [float] NULL,
	[Latest_PY] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[First_Policy_Year] [varchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[written_premium_policy] [float] NULL,
	[underwriter] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillplanshortDesc] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Office] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch_Region] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[zipcode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAICS] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Program_Code] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Business_Name] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Business_Desc] [char](72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Account_Name] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County] [nvarchar](511) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[program] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Division] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Major_group] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Industry_group] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_Desc] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Written_Premium_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County_Pop_Density_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIC_Producer_code] [int] NULL,
	[PIC_Commission_pct] [float] NULL,
	[Primary_Producer_code] [int] NULL,
	[Primary_Commission_pct] [float] NULL,
	[PIC_Producer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PIC_Producer_type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Primary_Producer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Primary_Producer_type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Commission_pct] [float] NULL,
	[Commission_dollars] [float] NULL,
	[Commission_Premiums] [float] NULL,
	[Renewal_Curr_MIPS_WP] [decimal](38, 2) NULL,
	[Renewal_calc_RateChangePrem_onExpiringTermPrem] [float] NULL,
	[Prior_MIPS_PolTerm_WP] [float] NULL,
	[Standard_Curr_MIPS_WP] [decimal](38, 2) NULL,
	[Standard_Premium_Curr] [float] NULL,
	[Benchmark_Curr_MIPS_WP] [decimal](38, 2) NULL,
	[Benchmark_NormPrem] [float] NULL,
	[Benchmark_Curr_Exposure] [float] NULL,
	[Price_Monitor_Renewal_Portion_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Portion_of_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Portion_of_CovGrp_St_Class_Monitored] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_CovGrp_St_Class_Monitored] [float] NULL,
	[Price_Monitor_Standard_Portion_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Standard_Changes_of_All_Cov_Monitored] [float] NULL,
	[Price_Monitor_Standard_Portion_of_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Standard_Cov_Grp_Monitored] [float] NULL,
	[Price_Monitor_Benchmark_Rate] [float] NULL,
	[Price_Monitor_Benchmark_CW_for_Class] [float] NULL,
	[Price_Monitor_Renewal_Changes_of_CovGrp_St_Class_Monitored_range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Price_Monitor_Standard_Cov_Grp_Monitored_range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Price_Monitor_Benchmark_Rate_to_CW_range] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Occurrence_Limit] [float] NULL,
	[GL_Aggregate_Limit] [float] NULL,
	[GL_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_Number_of_Locations] [int] NULL,
	[FA_Number_of_Buildings] [int] NULL,
	[FA_Building_Exposure] [float] NULL,
	[FA_Contents_Exposure] [float] NULL,
	[FA_Business_Interuption_Exposure] [float] NULL,
	[FA_Extra_Expense_Exposure] [float] NULL,
	[TIV] [float] NULL,
	[FA_Building_Prem] [float] NULL,
	[FA_Contents_Prem] [float] NULL,
	[FA_Deductible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Earned_TIV] [decimal](15, 2) NULL,
	[FA_Avg_Bld_Rate] [float] NULL,
	[FA_Avg_Cts_Rate] [float] NULL,
	[FA_Avg_Bld_Rate_rd2] [float] NULL,
	[FA_Avg_Bld_Rate_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_Avg_Cts_Rate_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_Constr_code_Tot_Exposure] [float] NULL,
	[FA_Constr_Code_Max_Exposure] [float] NULL,
	[FA_Constr_Code_Dominant] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_Constr_Code_Dominant_Percent] [float] NULL,
	[FA_Constr_Code_Dominant_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_protect_class_Tot_Exposure] [float] NULL,
	[FA_protect_class_Max_Exposure] [float] NULL,
	[FA_protect_class_Dominant] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_protect_class_Dominant_Percent] [float] NULL,
	[GL_Class_Apartments_Exposure] [float] NULL,
	[GL_Class_Apartments_RatingPrem] [float] NULL,
	[GL_Class_Apartments_Exposure_adj] [float] NULL,
	[GL_Class_Apartments_Garden_Exposure] [float] NULL,
	[GL_Class_Apartments_Garden_RatingPrem] [float] NULL,
	[GL_Class_Apartments_Garden_Exposure_adj] [float] NULL,
	[GL_Class_Swimming_Pools_Exposure] [float] NULL,
	[GL_Class_Swimming_Pools_RatingPrem] [float] NULL,
	[GL_Class_Swimming_Pools_Exposure_adj] [float] NULL,
	[GL_Class_Apartments_AvgRate] [float] NULL,
	[GL_Class_Apartments_Garden_AvgRate] [float] NULL,
	[GL_Class_Swimming_Pools_AvgRate] [float] NULL,
	[GL_Class_Apartments_AvgRate_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Class_Apartments_Garden_AvgRate_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Class_Swimming_Pools_AvgRate_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GL_Class_Apartments_AvgRate_rd0] [float] NULL,
	[GL_Class_Apartments_Garden_AvgRate_rd0] [float] NULL,
	[GL_Class_Swimming_Pools_AvgRate_rd0] [float] NULL,
	[Account_Loss_Ratio] [int] NULL,
	[Poor_Account_Indicator] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Count_of_Account_Numbers] [float] NULL,
	[Count_of_Account_Numbers_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
