IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BuildingRates_Property_Exposure]') AND type in (N'U'))
DROP TABLE [dbo].[BuildingRates_Property_Exposure]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BuildingRates_Property_Exposure]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BuildingRates_Property_Exposure](
	[Policy_Number] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Location] [smallint] NOT NULL,
	[Building] [smallint] NOT NULL,
	[State] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Territory] [int] NULL,
	[Class_Code] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AB_BG2_Exposure] [decimal](15, 2) NULL,
	[AB_BG2_Construction_Code] [smallint] NULL,
	[AB_BG2_Protection_Class] [smallint] NULL,
	[AB_BG2_AQS_Premium] [float] NULL,
	[AB_BG2_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AB_SCoL_Exposure] [decimal](15, 2) NULL,
	[AB_SCoL_AQS_Premium] [float] NULL,
	[FB_Exposure] [decimal](15, 2) NULL,
	[FB_Construction_Code] [smallint] NULL,
	[FB_Protection_Class] [smallint] NULL,
	[FB_AQS_Premium] [float] NULL,
	[FB_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UCAB_Exposure] [decimal](15, 2) NULL,
	[UCAB_Construction_Code] [smallint] NULL,
	[UCAB_Protection_Class] [smallint] NULL,
	[UCAB_AQS_Premium] [float] NULL,
	[UCAB_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AC_BG2_Exposure] [decimal](15, 2) NULL,
	[AC_BG2_AQS_Premium] [float] NULL,
	[AC_BG2_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AC_SCoL_Exposure] [decimal](15, 2) NULL,
	[AC_SCoL_AQS_Premium] [float] NULL,
	[FC_Exposure] [decimal](15, 2) NULL,
	[FC_Construction_Code] [smallint] NULL,
	[FC_Protection_Class] [smallint] NULL,
	[FC_AQS_Premium] [float] NULL,
	[FC_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UCAC_Exposure] [decimal](15, 2) NULL,
	[UCAC_Construction_Code] [smallint] NULL,
	[UCAC_Protection_Class] [smallint] NULL,
	[UCAC_AQS_Premium] [float] NULL,
	[UCAC_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AEE_Exposure] [decimal](15, 2) NULL,
	[AI_Exposure] [decimal](15, 2) NULL,
	[AI_AQS_Premium] [float] NULL,
	[AI_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FEE_Exposure] [decimal](15, 2) NULL,
	[FI_Exposure] [decimal](15, 2) NULL,
	[FI_AQS_Premium] [float] NULL,
	[FI_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UCAE_Exposure] [decimal](15, 2) NULL,
	[UCAI_Exposure] [decimal](15, 2) NULL,
	[UCAI_AQS_Premium] [float] NULL,
	[UCAI_Deductible] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FA_Building_Exposure] [float] NULL,
	[FA_Contents_Exposure] [float] NULL,
	[FA_Business_Interuption_Exposure] [float] NULL,
	[FA_Extra_Expense_Exposure] [float] NULL,
	[FA_Deductible] [int] NULL,
	[Address] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Prior_Policy_Number] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIV] [decimal](15, 2) NULL,
	[Inforce_TIV] [float] NULL,
	[Prior_TIV] [decimal](15, 2) NULL,
	[Change_in_TIV] [decimal](15, 2) NULL,
	[Construction_Code] [int] NULL,
	[Protection_Class] [int] NULL,
	[constr_Code_1_Exposure] [float] NULL,
	[constr_Code_2_Exposure] [float] NULL,
	[constr_Code_3_Exposure] [float] NULL,
	[constr_Code_4_Exposure] [float] NULL,
	[constr_Code_5_Exposure] [float] NULL,
	[constr_Code_6_Exposure] [float] NULL,
	[constr_Code_7_Exposure] [float] NULL,
	[constr_Code_8_Exposure] [float] NULL,
	[constr_Code_9_Exposure] [float] NULL,
	[constr_Code_10_Exposure] [float] NULL,
	[protect_class_1_Exposure] [float] NULL,
	[protect_class_2_Exposure] [float] NULL,
	[protect_class_3_Exposure] [float] NULL,
	[protect_class_4_Exposure] [float] NULL,
	[protect_class_5_Exposure] [float] NULL,
	[protect_class_6_Exposure] [float] NULL,
	[protect_class_7_Exposure] [float] NULL,
	[protect_class_8_Exposure] [float] NULL,
	[protect_class_9_Exposure] [float] NULL,
	[protect_class_10_Exposure] [float] NULL,
	[Policy_ID] [int] NULL,
	[UC] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Product] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Wind] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Wind_Deductible] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hurricane_Deductible] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Tier] [tinyint] NULL,
	[Distance_to_Shore] [float] NULL,
	[Distance_to_Shore_Range] [varchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hurricane_Map_Legend] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Wind_Map_Legend] [varchar](55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hail_Storm_Frequency_Range] [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Wildfire_Tier] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Implied_Rate] [float] NULL,
	[EQ_Premium] [float] NULL,
	[Flood_Premium] [int] NULL,
	[Terrorism_Premium] [int] NULL,
	[Population_Density_Zone] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Population_Density_Zone_Metro_Exposure] [float] NULL,
	[Population_Density_Zone_Urban_Exposure] [float] NULL,
	[Population_Density_Zone_Suburban_Exposure] [float] NULL,
	[Population_Density_Zone_SemiSuburban_Exposure] [float] NULL,
	[Population_Density_Zone_Rural_Exposure] [float] NULL,
	[ZIP_Hail_Frequency] [varchar](23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hail_A_Exposure] [float] NULL,
	[Hail_B_Exposure] [float] NULL,
	[Hail_C_Exposure] [float] NULL,
	[Hail_D_Exposure] [float] NULL,
	[Hail_E_Exposure] [float] NULL,
	[Hail_F_Exposure] [float] NULL,
	[Hail_G_Exposure] [float] NULL,
	[Hail_H_Exposure] [float] NULL,
	[MinUCRate] [float] NULL,
	[MaxUCRate] [float] NULL,
	[MinUCPrem] [float] NULL,
	[MaxUCPrem] [float] NULL
) ON [PRIMARY]
END
GO
