IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Policy_PATHID_Information_LossRatios]') AND type in (N'U'))
DROP TABLE [dbo].[Policy_PATHID_Information_LossRatios]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Policy_PATHID_Information_LossRatios]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Policy_PATHID_Information_LossRatios](
	[accountnumber] [int] NULL,
	[DivisionName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[productcode] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prevpolicynumber] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_2] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_3] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_4] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_5] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_6] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_7] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[prior_policynumber_8] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[policy_premium] [float] NULL,
	[prevpolicy_premium] [float] NULL,
	[policy_premium_2] [float] NULL,
	[policy_premium_3] [float] NULL,
	[policy_premium_4] [float] NULL,
	[policy_premium_5] [float] NULL,
	[policy_premium_6] [float] NULL,
	[policy_premium_7] [float] NULL,
	[policy_premium_8] [float] NULL,
	[Effectivedate] [datetime] NULL,
	[prevpolicy_Effectivedate] [datetime] NULL,
	[policy_Effectivedate_2] [datetime] NULL,
	[policy_Effectivedate_3] [datetime] NULL,
	[policy_Effectivedate_4] [datetime] NULL,
	[policy_Effectivedate_5] [datetime] NULL,
	[policy_Effectivedate_6] [datetime] NULL,
	[policy_Effectivedate_7] [datetime] NULL,
	[policy_Effectivedate_8] [datetime] NULL,
	[Expirationdate] [datetime] NULL,
	[prevpolicy_Expirationdate] [datetime] NULL,
	[policy_Expirationdate_2] [datetime] NULL,
	[policy_Expirationdate_3] [datetime] NULL,
	[policy_Expirationdate_4] [datetime] NULL,
	[policy_Expirationdate_5] [datetime] NULL,
	[policy_Expirationdate_6] [datetime] NULL,
	[policy_Expirationdate_7] [datetime] NULL,
	[policy_Expirationdate_8] [datetime] NULL,
	[Yr_MM_30_60_days] [int] NULL,
	[Yr_MM_60_90_days] [int] NULL,
	[Yr_MM_90_120_days] [int] NULL,
	[Loss_max_YRMM] [int] NULL,
	[Accountstatistic_LossRatio] [float] NULL,
	[EarnedPremium_Acct_CurrEval] [float] NULL,
	[Incurred_LossALAE_Acct_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_CurrEval_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_Div_CurrEval] [float] NULL,
	[Incurred_LossALAE_Acct_Div_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_Div_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_Div_CurrEval_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_Div_Prod_CurrEval] [float] NULL,
	[Incurred_LossALAE_Acct_Div_Prod_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_Div_Prod_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_Div_Prod_CurrEval_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_60_90] [float] NULL,
	[Incurred_LossALAE_Acct_60_90] [float] NULL,
	[Incurred_LossRatio_Acct_60_90] [float] NULL,
	[Incurred_LossRatio_Acct_60_90_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_Div_60_90] [float] NULL,
	[Incurred_LossALAE_Acct_Div_60_90] [float] NULL,
	[Incurred_LossRatio_Acct_Div_60_90] [float] NULL,
	[Incurred_LossRatio_Acct_Div_60_90_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_Div_Prod_60_90] [float] NULL,
	[Incurred_LossALAE_Acct_Div_Prod_60_90] [float] NULL,
	[Incurred_LossRatio_Acct_Div_Prod_60_90] [float] NULL,
	[Incurred_LossRatio_Acct_Div_Prod_60_90_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_90_120] [float] NULL,
	[Incurred_LossALAE_Acct_90_120] [float] NULL,
	[Incurred_LossRatio_Acct_90_120] [float] NULL,
	[Incurred_LossRatio_Acct_90_120_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_Div_90_120] [float] NULL,
	[Incurred_LossALAE_Acct_Div_90_120] [float] NULL,
	[Incurred_LossRatio_Acct_Div_90_120] [float] NULL,
	[Incurred_LossRatio_Acct_Div_90_120_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_Div_Prod_90_120] [float] NULL,
	[Incurred_LossALAE_Acct_Div_Prod_90_120] [float] NULL,
	[Incurred_LossRatio_Acct_Div_Prod_90_120] [float] NULL,
	[Incurred_LossRatio_Acct_Div_Prod_90_120_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Acct_5UWYr_CurrEval] [float] NULL,
	[Incurred_LossALAE_Acct_5UWYr_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_5UWYr_CurrEval] [float] NULL,
	[Incurred_LossRatio_Acct_5UWYr_CurrEval_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Incurred_LossRatio_Acct_5UWYr_CurrEval_Range_PriorPol] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EarnedPremium_Pol_5Yr_Div_60_90] [float] NULL,
	[Incurred_LossALAE_Pol_5Yr_Div_60_90] [float] NULL,
	[Incurred_LossRatio_Pol_5Yr_Div_60_90] [float] NULL,
	[Incurred_LossRatio_Pol_5Yr_Div_60_90_Range] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Incurred_LossRatio_Pol_5Yr_Div_60_90_Range_PriorPol] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
