IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'PHLYNT\ACTUARIAL SERVICES')
DROP USER [PHLYNT\ACTUARIAL SERVICES]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'PHLYNT\ACTUARIAL SERVICES')
CREATE USER [PHLYNT\ACTUARIAL SERVICES] FOR LOGIN [PHLYNT\ACTUARIAL SERVICES]
GO
sys.sp_addrolemember @rolename = N'db_owner', @membername = N'PHLYNT\ACTUARIAL SERVICES'
GO
