IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Individual_Accounts_PriceMonitor_UC_View_1]'))
DROP VIEW [dbo].[Individual_Accounts_PriceMonitor_UC_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Individual_Accounts_PriceMonitor_UC_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.Individual_Accounts_PriceMonitor_UC_View_1
AS
SELECT     dbo.Policy_PATHID_Information.accountnumber, dbo.Policy_PATHID_Information.accountname, dbo.Policy_PATHID_Information.regioncode, 
                      dbo.Policy_PATHID_Information.regiondesc, dbo.Policy_PATHID_Information.PICProducer, dbo.Policy_PATHID_Information.PrimaryProducer, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PolicyNumber, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.SourceSystemPolicyKey, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PolicySnapshotID, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RatingModule, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PriorPolicyNumber, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.SnapShotType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PolicyEffectiveDate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PolicyExpirationDate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Product, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.SIC, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PrimaryCommissionPct, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PICCommissionPct, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.InsurableEffectiveDate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.InsurableExpirationDate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Deductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Subline, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ClassCode, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Premium, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Exposure, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.InsurableID, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LocationAddress1, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LocationAddress2, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LocationCity, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LocationState, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LocationZip, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LocationCounty, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PriorInsurableID, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.CoverageCode, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Territory, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ProtectionClass, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ISOClass, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ConstructionCode, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PremiumState, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ConstructionDescription, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.CoInsurance, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AQSBuildingSequence, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AQSOccupancySequence, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AQSLocationSequence, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AQSBlanketSequence, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PriorInsurableIDMatchType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.SourceSystemKeyValue, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PremiumProxy, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExposureProxy, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PremiumOverride, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.IssuanceDateTime, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.WindHailExclusion, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.WindHailDeductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.HurricaneDeductible, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NamedStormDeductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ApplicableHurricaneDeductibleToTIV, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingDisasterExposure, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingClimaticHazards, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingSpecialOccupancyHazard, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingLackOfPrivateProtection, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingInadequatePrivateProtection, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingExternalExposure, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingConstruction, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingCombustibilitySusceptibility, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingArrangeOfSpecificInsurance, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingTransitFloatingEquipment, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingLowerDeductible, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingCoverExcludedProperty, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsDisasterExposure, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsClimaticHazards, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsSpecialOccupancyHazard, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsLackOfPrivateProtection, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsInadequatePrivateProtection, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsExternalExposure, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsConstruction, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsCombustibilitySusceptibility, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsArrangeOfSpecificInsurance, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsTransitFloatingEquipment, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsLowerDeductible, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ContentsCoverExcludedProperty, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.CoverageType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeOfRisk, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.OrdinaryPayroll, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AgreedValueIndicator, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NumberOfDays, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.MonthlyLimitTypeOfRisk, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.MonthlyLimitation, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AgreedValueLimit, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExtraExpenseInd, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PaymentOption, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.BuildingTIV, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeDeductiblePercent, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeAnyOnePremisesLimit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakePremisesPerYearLimit, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeDeficiencyPoints, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeSprinklerOnly, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeSprinklerDeficiencyPoints, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeSprinklerAnyOnePremisesLimit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeSprinklerPremisesPerYearLimit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FloodDeficiencyPoints, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FloodAnyOnePremisesLimit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FloodPremisesPerYearLimit, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FloodBuildingDeductible, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FloodContentsDeductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ConstructionYear, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NumberOfStories, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RoofAnchor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RoofCovering, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RoofFramingType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RoofType, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RoofConstructionYear, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.WindResistanceWindows, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakePolicyDeductible, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.StandardCombinedMod, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PolicyTerm, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PremiumTerm, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DedFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AcctRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AcctRate_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ACR_VLPRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AdjustedExperienceCredit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AdjustedExperienceCredit_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AgreedValue, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.AgreedValueFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ClimaticDeficiencyRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.CoinsuranceRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeductibleCredit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeductibleCredit_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeductibleFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeductibleFactor_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeductiblePlusAdjusted, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeductibleValue, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeficiencyFinalBaseRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeficiencyRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.DeficiencyRate_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Departure, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EightyPercentMLR, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExpenseMod, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExperienceCredit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExperienceCredit_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExperienceDebit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExperienceDebit_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExperiencePremium, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExperiencePremium_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ExtensionPeriodFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FinalBaseRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FinalRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FireSurcharge, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.HurricaneDeductibleCredit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.IRPM1, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.IRPM2, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.IRPM3, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LossLimit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LossLimit_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.LossLimitCredit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.MajorFinalBaseRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.MajorLossRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.MajorLossRate_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.MonthlyLimitFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NLRBaseMinRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NLRBaseMinRate_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NLRBaseRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NLRBaseRate_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NormalLossRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.NormalLossRate_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.OptionFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.OrdinaryPayrollFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ResidentialConstructionCredit, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ResidentialConstructionFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.RMF, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Step1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Step2, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.Table7AFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeCoins, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeCoinsEEX, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeCoins80Percent, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeCoins80PercentEEX, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.WindLossCredit, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.WindLossFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ActualBaseRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeDPR, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.EarthquakeSprinklerDPR, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.ModifiedRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.FloodDPR, PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeCoins_Selected, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.TypeCoins_Selected_MLR
FROM         dbo.Policy_PATHID_Information LEFT OUTER JOIN
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataUC ON 
                      dbo.Policy_PATHID_Information.policynumber = PriceMonitorSystem.dbo.PriceMonitorBaseDataUC.PolicyNumber INNER JOIN
                      dbo.Individual_Accounts_for_Reports_View_2 ON dbo.Policy_PATHID_Information.accountnumber = dbo.Individual_Accounts_for_Reports_View_2.accountnumber
' 
GO
