IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PVCD_ClaimsMod_View_1]'))
DROP VIEW [dbo].[PVCD_ClaimsMod_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PVCD_ClaimsMod_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.PVCD_ClaimsMod_View_1
AS
SELECT     dbo.ALL_POLICIES_12_premium_summary_September.statecode, dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_September.productcode, dbo.ALL_POLICIES_12_premium_summary_September.Fiscal_AY_Year, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.currentwrittenpremium) AS currentwrittenpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.currentearnedpremium) AS currentearnedpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Policy_count_Reporting_Coverage) AS Policy_count_Reporting_Coverage, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Incurred_Loss_ALAE_with_SS_NonCat) AS Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat) 
                      AS Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, SUM(dbo.ALL_POLICIES_12_premium_summary_September.Reported_Claims) 
                      AS Reported_Claims, SUM(dbo.ALL_POLICIES_12_premium_summary_September.Incurred_Claims) AS Incurred_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Commission_dollars) AS Commission_dollars, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Commission_Premiums) AS Commission_Premiums, 
                      dbo.Policy_Information_ALL_POLICIES_September.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_September.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_September.Branch_Region, dbo.Policy_Information_ALL_POLICIES_September.program, 
                      dbo.Policy_Information_ALL_POLICIES_September.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_September.product_group, dbo.Policy_Information_ALL_POLICIES_September.Primary_Umbrella, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Earned_Buildings) AS Earned_Buildings, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Earned_Locations) AS Earned_Locations, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Earned_TIV) AS Earned_TIV, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_September.Primary_Producer, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Policy_count_All_Cov_Combined) AS Policy_count_All_Cov_Combined, 
                      dbo.Policy_Information_ALL_POLICIES_September.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_September.Account_RepLoss_Ratio_Working_Cover_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Policy_count_Coverage_Group) AS Policy_count_Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_September.accountnumber, dbo.Policy_Information_ALL_POLICIES_September.Primary_Producer_type, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Incurred_Loss_ALAE_with_SS) AS Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Capped_Incurred_Loss_ALAE_with_SS) AS Capped_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Ult_LDF_Incurred_Loss_ALAE_with_SS) AS Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS) 
                      AS Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, dbo.ALL_POLICIES_12_premium_summary_September.policynumber, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Form, dbo.Policy_Information_ALL_POLICIES_September.Endorsement_Elite_YN, 
                      dbo.Policy_Information_ALL_POLICIES_September.Account_Name, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.Incurred_Loss_ALAE_with_SS_CatOnly) AS Incurred_Loss_ALAE_with_SS_CatOnly, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Retro_Date_Applies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.EEO1_Report_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Board_Experience_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Employment_Policies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Claims_Past_5yrs_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Full_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Part_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Temporary_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Insider_Shareholder_Percent_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Employee_Salary_GT100k_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Salary_100K_to_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Percent_of_Part_Time_and_Temp_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Total_Participants_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Total_Claims_Range, dbo.Policy_Information_PVCD_September.PVCD_PVDO_Limit, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Limit, dbo.Policy_Information_PVCD_September.PVCD_PVDO_Alt_Retention, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Alt_Retention, dbo.Policy_Information_PVCD_September.PVCD_PVDO_RatingClass, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_RatingClass, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Num_of_Employees_Range, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amendment_End_Y_N, dbo.Policy_Information_PVCD_September.PVCD_Partnership_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_ProPak_Elite72_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_ProPak_Elite73_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Circumstance_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Professional_Services_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Sexual_Abuse_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_BullsEye_ProPak_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amended_Def_of_Employee_Incl_Ind_Contractors_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amend_of_ExclusionK_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amend_of_Severability_Provision_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Third_Party_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Punitive_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Medical_Malpractice_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Insurance_EO_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Full_Securities_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_FAILURE_TO_MAINT_INSUR_EXCLUSION_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Bankruptcy_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Shareholder_End_Y_N, dbo.Policy_Information_PVCD_September.PVCD_Past_Acts_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_No_Liab_Retent_Waiver_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Delete_Consent_End_Y_N, dbo.Policy_Information_PVCD_September.PVCD_Election_ERP_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Damages_Only_Retention_End_Y_N, 
                      dbo.Policy_Information_ALL_POLICIES_September.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_September.Branch_Office, 
                      dbo.Policy_Information_PVCD_September.PVCD_Business_Type, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Breach_of_Contract_Loss) AS COL_Breach_of_Contract_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Discrimination_Loss) AS COL_Discrimination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Wrongful_Termination_Loss) AS COL_Wrongful_Termination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Harrassment_Loss) AS COL_Harrassment_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_SLD_All_Other_Loss) AS COL_SLD_All_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_SLD_All_Other_Count) AS COL_SLD_All_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Harrassment_Count) AS COL_Harassment_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Wrongful_Termination_Count) AS COL_WrongfulTermination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Discrimination_Count) AS COL_Discrimination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_September.COL_Breach_of_Contract_Count) AS COL_Breach_of_Contract_Count, 
                      dbo.Policy_Information_ALL_POLICIES_September.First_Policy_Year, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_DO_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_DO_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_EPL_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Fiduciary_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Worplace_Violence_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Internet_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Internet_Other_Loss, dbo.Policy_Information_PVCD_September.PVCD_PVDO_ZoneMod, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_ZoneMod, dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Num_of_Employees, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Fiscal_AY_Month_Ending, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_September.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_September.PIC_Producer, dbo.Policy_Information_ALL_POLICIES_September.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_September.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_September.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_September.DivisionName, dbo.Policy_Information_PVCD_September.PVCD_County_DO, 
                      dbo.Policy_Information_PVCD_September.PVCD_County_EPL, 
                      dbo.Policy_Information_ALL_POLICIES_September.Written_Premium_Range_for_Product, dbo.Policy_PATHID_Information.PICProducer, 
                      dbo.Policy_PATHID_Information.programdesc
FROM         dbo.PVDO_ClaimsModAccountNumberList LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_September ON 
                      dbo.PVDO_ClaimsModAccountNumberList.AccountNumber = dbo.Policy_Information_ALL_POLICIES_September.accountnumber LEFT OUTER JOIN
                      dbo.Policy_PATHID_Information ON 
                      dbo.Policy_Information_ALL_POLICIES_September.policynumber = dbo.Policy_PATHID_Information.policynumber RIGHT OUTER JOIN
                      dbo.ALL_POLICIES_12_premium_summary_September LEFT OUTER JOIN
                      dbo.Policy_Information_PVCD_September ON 
                      dbo.ALL_POLICIES_12_premium_summary_September.policynumber = dbo.Policy_Information_PVCD_September.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_Underwriting_Check_List_September ON 
                      dbo.ALL_POLICIES_12_premium_summary_September.policynumber = dbo.Policy_Information_Underwriting_Check_List_September.policynumber ON 
                      dbo.Policy_Information_ALL_POLICIES_September.policynumber = dbo.ALL_POLICIES_12_premium_summary_September.policynumber LEFT OUTER JOIN
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September ON 
                      dbo.ALL_POLICIES_12_premium_summary_September.policynumber = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.policynumber
                       AND 
                      dbo.ALL_POLICIES_12_premium_summary_September.productcode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.Productcode
                       AND 
                      dbo.ALL_POLICIES_12_premium_summary_September.statecode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.statecode AND
                       dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Group = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.coverage_group
GROUP BY dbo.ALL_POLICIES_12_premium_summary_September.statecode, dbo.ALL_POLICIES_12_premium_summary_September.policynumber, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Form, dbo.ALL_POLICIES_12_premium_summary_September.productcode, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Fiscal_AY_Year, dbo.Policy_Information_ALL_POLICIES_September.New_Renew_Tail, 
                      dbo.Policy_Information_ALL_POLICIES_September.Renew_New_Auto, dbo.Policy_Information_ALL_POLICIES_September.Branch_Region, 
                      dbo.Policy_Information_ALL_POLICIES_September.program, dbo.Policy_Information_ALL_POLICIES_September.Written_Premium_Range, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Group, dbo.Policy_Information_ALL_POLICIES_September.product_group, 
                      dbo.Policy_Information_ALL_POLICIES_September.Primary_Umbrella, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_September.Primary_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_September.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_September.Account_RepLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_September.accountnumber, dbo.Policy_Information_ALL_POLICIES_September.Primary_Producer_type, 
                      dbo.Policy_Information_ALL_POLICIES_September.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_September.Account_Name, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Retro_Date_Applies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.EEO1_Report_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Board_Experience_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Employment_Policies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Claims_Past_5yrs_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Full_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Part_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Temporary_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Number_of_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Insider_Shareholder_Percent_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Employee_Salary_GT100k_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Salary_100K_to_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Percent_of_Part_Time_and_Temp_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Total_Participants_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Total_Claims_Range, dbo.Policy_Information_PVCD_September.PVCD_PVDO_Limit, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Limit, dbo.Policy_Information_PVCD_September.PVCD_PVDO_Alt_Retention, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Alt_Retention, dbo.Policy_Information_PVCD_September.PVCD_PVDO_RatingClass, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_RatingClass, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Num_of_Employees_Range, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amendment_End_Y_N, dbo.Policy_Information_PVCD_September.PVCD_Partnership_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_ProPak_Elite72_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_ProPak_Elite73_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Circumstance_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Professional_Services_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Sexual_Abuse_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_BullsEye_ProPak_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amended_Def_of_Employee_Incl_Ind_Contractors_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amend_of_ExclusionK_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Amend_of_Severability_Provision_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Third_Party_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Punitive_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Medical_Malpractice_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Insurance_EO_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Full_Securities_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_FAILURE_TO_MAINT_INSUR_EXCLUSION_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Bankruptcy_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Shareholder_End_Y_N, dbo.Policy_Information_PVCD_September.PVCD_Past_Acts_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_No_Liab_Retent_Waiver_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Delete_Consent_End_Y_N, dbo.Policy_Information_PVCD_September.PVCD_Election_ERP_End_Y_N, 
                      dbo.Policy_Information_PVCD_September.PVCD_Damages_Only_Retention_End_Y_N, dbo.Policy_Information_PVCD_September.New_Renew_Tail, 
                      dbo.Policy_Information_PVCD_September.Renew_New_Auto, dbo.Policy_Information_PVCD_September.Branch_Region, 
                      dbo.Policy_Information_ALL_POLICIES_September.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_September.Branch_Office, 
                      dbo.Policy_Information_PVCD_September.PVCD_Business_Type, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Incurred_Loss_ALAE_with_SS_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_September.First_Policy_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Capped_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Incurred_Claims, 
                      dbo.Policy_Information_Underwriting_Check_List_September.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_September.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.ALL_POLICIES_12_premium_summary_September.experienceproduct, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_DO_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_DO_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_EPL_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Fiduciary_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Worplace_Violence_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Internet_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_September.COL_Internet_Other_Loss, dbo.Policy_Information_PVCD_September.PVCD_PVDO_ZoneMod, 
                      dbo.Policy_Information_PVCD_September.PVCD_PVEPL_ZoneMod, dbo.Policy_Information_PVCD_September.PVCD_PVEPL_Num_of_Employees, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Fiscal_AY_Month_Ending, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_September.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_September.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_September.PIC_Producer, dbo.Policy_Information_ALL_POLICIES_September.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_September.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_September.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_September.DivisionName, dbo.Policy_Information_PVCD_September.PVCD_ZoneNum_EPL, 
                      dbo.Policy_Information_PVCD_September.PVCD_ZoneNum_DO, dbo.Policy_Information_PVCD_September.PVCD_ZipCode_DO, 
                      dbo.Policy_Information_PVCD_September.PVCD_ZipCode_EPL, dbo.Policy_Information_PVCD_September.PVCD_State_DO, 
                      dbo.Policy_Information_PVCD_September.PVCD_State_EPL, dbo.Policy_Information_PVCD_September.PVCD_County_DO, 
                      dbo.Policy_Information_PVCD_September.PVCD_County_EPL, 
                      dbo.Policy_Information_ALL_POLICIES_September.Written_Premium_Range_for_Product, dbo.Policy_PATHID_Information.PICProducer, 
                      dbo.Policy_PATHID_Information.programdesc
HAVING      (dbo.ALL_POLICIES_12_premium_summary_September.Coverage_Reporting_group = ''D&O'') AND 
                      (dbo.ALL_POLICIES_12_premium_summary_September.Fiscal_AY_Year > ''2006'') AND 
                      (dbo.Policy_Information_ALL_POLICIES_September.Renew_New_Auto = ''Automatic Renewal'') OR
                      (dbo.Policy_Information_ALL_POLICIES_September.Renew_New_Auto = ''Renewal'')
' 
GO
