IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[NPDO_ALL_Lines_View_1_State_CA_D&O]'))
DROP VIEW [dbo].[NPDO_ALL_Lines_View_1_State_CA_D&O]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[NPDO_ALL_Lines_View_1_State_CA_D&O]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.[NPDO_ALL_Lines_View_1_State_CA_D&O]
AS
SELECT     dbo.ALL_POLICIES_12_premium_summary_April.statecode, dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_April.productcode, dbo.ALL_POLICIES_12_premium_summary_April.Fiscal_AY_Year, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.currentwrittenpremium) AS currentwrittenpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.currentearnedpremium) AS currentearnedpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Policy_count_Reporting_Coverage) AS Policy_count_Reporting_Coverage, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Incurred_Loss_ALAE_with_SS_NonCat) AS Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat) 
                      AS Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, SUM(dbo.ALL_POLICIES_12_premium_summary_April.Reported_Claims) 
                      AS Reported_Claims, SUM(dbo.ALL_POLICIES_12_premium_summary_April.Incurred_Claims) AS Incurred_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Commission_dollars) AS Commission_dollars, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Commission_Premiums) AS Commission_Premiums, 
                      dbo.Policy_Information_ALL_POLICIES_April.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_April.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_April.Branch_Region, dbo.Policy_Information_ALL_POLICIES_April.program, 
                      dbo.Policy_Information_ALL_POLICIES_April.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_April.product_group, dbo.Policy_Information_ALL_POLICIES_April.Primary_Umbrella, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Earned_Buildings) AS Earned_Buildings, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Earned_Locations) AS Earned_Locations, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Earned_TIV) AS Earned_TIV, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_April.Primary_Producer, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Policy_count_All_Cov_Combined) AS Policy_count_All_Cov_Combined, 
                      dbo.Policy_Information_ALL_POLICIES_April.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_April.Account_RepLoss_Ratio_Working_Cover_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Policy_count_Coverage_Group) AS Policy_count_Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_April.accountnumber, dbo.Policy_Information_ALL_POLICIES_April.Primary_Producer_type, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Incurred_Loss_ALAE_with_SS) AS Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Capped_Incurred_Loss_ALAE_with_SS) AS Capped_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Ult_LDF_Incurred_Loss_ALAE_with_SS) AS Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS) AS Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_April.policynumber, dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Form, 
                      dbo.Policy_Information_ALL_POLICIES_April.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_April.Account_Name, 
                      dbo.Policy_Information_ALL_POLICIES_April.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_April.Branch_Office, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Breach_of_Contract_Loss) AS COL_Breach_of_Contract_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Discrimination_Loss) AS COL_Discrimination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Wrongful_Termination_Loss) AS COL_Wrongful_Termination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Harrassment_Loss) AS COL_Harrassment_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_SLD_All_Other_Loss) AS COL_SLD_All_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_SLD_All_Other_Count) AS COL_SLD_All_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Harrassment_Count) AS COL_Harassment_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Wrongful_Termination_Count) AS COL_WrongfulTermination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Discrimination_Count) AS COL_Discrimination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Breach_of_Contract_Count) AS COL_Breach_of_Contract_Count, 
                      dbo.Policy_Information_ALL_POLICIES_April.First_Policy_Year, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_DO_Other_Count) AS COL_DO_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_DO_Other_Loss) AS COL_DO_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_EPL_Other_Count) AS COL_EPL_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_EPL_Other_Loss) AS COL_EPL_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Fiduciary_Other_Count) AS COL_Fiduciary_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Fiduciary_Other_Loss) AS COL_Fiduciary_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Worplace_Violence_Other_Count) AS COL_Worplace_Violence_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Worplace_Violence_Other_Loss) AS COL_Worplace_Violence_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Internet_Other_Count) AS COL_Internet_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_April.COL_Internet_Other_Loss) AS COL_Internet_Other_Loss, 
                      dbo.Policy_Information_FF_April.FF_DO_Limit, dbo.Policy_Information_FF_April.FF_EPL_Limit, dbo.Policy_Information_FF_April.FF_DO_Alt_Retention, 
                      dbo.Policy_Information_FF_April.FF_EPL_Num_of_Employees_Range, dbo.Policy_Information_FF_April.TrimBusiness_Type, 
                      dbo.Policy_Information_FF_April.FF_DO_RatingClass, dbo.Policy_Information_FF_April.FF_EPL_RatingClass, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Financials_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Supplemental_Claim_Form_Loss_Run_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Bylaws_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Form_5500_YN, dbo.Policy_Information_FF_April.FF_EPL_Alt_Retention, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Number_of_Years_in_Operation, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Plan_Assets, dbo.Policy_Information_Underwriting_Check_List_April.Turnover_Rate, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Turnover_Rate_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.No_Loss_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.No_Prior_Coverage_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Supp_Claim_Form_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Website_Transactional_E_Commerce_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Website_Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Transaction_E_Commerce_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Tax_Exempt_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Standard_Setting_or_Member_Certification_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Security_Precautions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Magazines_Periodicals_or_Newsletters_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Proper_Employment_Procedures_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Product_Research_or_Development_Testing_Certif_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Positive_Fund_Balance_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Peer_Review_or_Disciplinary_Action_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Merger_Acquisition_or_Consolidation_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.List_of_D_and_Os_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Employment_Application_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Employment_Application_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Disciplinary_Action_from_Peer_Review_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Disciplinary_Administrative_or_Criminal_Actions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Insurance_Programs_For_Members_YN, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Last_Reporting_Year, dbo.ALL_POLICIES_12_premium_summary_April.Last_Reporting_Month, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Fiscal_AY_Month_Ending, dbo.Policy_Information_ALL_POLICIES_April.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_April.DivisionName, dbo.Policy_Information_ALL_POLICIES_April.BusinessClassDesc, 
                      dbo.Policy_Information_ALL_POLICIES_April.Source_Detail_Name, dbo.Policy_Information_ALL_POLICIES_April.PIC_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_April.underwriter, CONVERT(int, dbo.Policy_Information_FF_April.FF_EPL_Limit) AS EPL_Limit_int, 
                      dbo.Policy_Information_FF_April.FF_DO_Alt_Retention_int, dbo.Policy_Information_FF_April.FF_EPL_Alt_Retention_int, 
                      dbo.Policy_Information_FF_April.FF_EPL_Limit_int, dbo.Policy_Information_ALL_POLICIES_April.Written_Premium_Range_for_Product, 
                      dbo.Policy_Information_ALL_POLICIES_April.policyEffectivedate, dbo.Policy_Information_ALL_POLICIES_April.policyexpirationdate, 
                      dbo.Policy_Information_ALL_POLICIES_April.Latest_PY, dbo.Policy_Information_ALL_POLICIES_April.policy_effective_month, 
                      dbo.Policy_Information_ALL_POLICIES_April.policy_effective_year
FROM         dbo.ALL_POLICIES_12_premium_summary_April LEFT OUTER JOIN
                      dbo.Policy_Information_FF_April ON 
                      dbo.ALL_POLICIES_12_premium_summary_April.policynumber = dbo.Policy_Information_FF_April.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_Underwriting_Check_List_April ON 
                      dbo.ALL_POLICIES_12_premium_summary_April.policynumber = dbo.Policy_Information_Underwriting_Check_List_April.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_April ON 
                      dbo.ALL_POLICIES_12_premium_summary_April.policynumber = dbo.Policy_Information_ALL_POLICIES_April.policynumber LEFT OUTER JOIN
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April ON 
                      dbo.ALL_POLICIES_12_premium_summary_April.policynumber = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.policynumber AND 
                      dbo.ALL_POLICIES_12_premium_summary_April.productcode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.Productcode AND 
                      dbo.ALL_POLICIES_12_premium_summary_April.statecode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.statecode AND 
                      dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Group = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.coverage_group
GROUP BY dbo.ALL_POLICIES_12_premium_summary_April.statecode, dbo.ALL_POLICIES_12_premium_summary_April.policynumber, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Reporting_group, dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Form, 
                      dbo.ALL_POLICIES_12_premium_summary_April.productcode, dbo.ALL_POLICIES_12_premium_summary_April.Fiscal_AY_Year, 
                      dbo.Policy_Information_ALL_POLICIES_April.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_April.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_April.Branch_Region, dbo.Policy_Information_ALL_POLICIES_April.program, 
                      dbo.Policy_Information_ALL_POLICIES_April.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_April.product_group, dbo.Policy_Information_ALL_POLICIES_April.Primary_Umbrella, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_April.Primary_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_April.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_April.Account_RepLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_April.accountnumber, dbo.Policy_Information_ALL_POLICIES_April.Primary_Producer_type, 
                      dbo.Policy_Information_ALL_POLICIES_April.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_April.Account_Name, 
                      dbo.Policy_Information_ALL_POLICIES_April.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_April.Branch_Office, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Incurred_Loss_ALAE_with_SS_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_April.First_Policy_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Capped_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Incurred_Claims, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_April.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.Policy_Information_FF_April.FF_DO_Limit, dbo.Policy_Information_FF_April.FF_EPL_Limit, dbo.Policy_Information_FF_April.FF_DO_Alt_Retention, 
                      dbo.Policy_Information_FF_April.FF_EPL_Num_of_Employees_Range, dbo.Policy_Information_FF_April.TrimBusiness_Type, 
                      dbo.Policy_Information_FF_April.FF_DO_RatingClass, dbo.Policy_Information_FF_April.FF_EPL_RatingClass, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Financials_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Supplemental_Claim_Form_Loss_Run_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Bylaws_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Form_5500_YN, dbo.Policy_Information_FF_April.FF_EPL_Alt_Retention, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Number_of_Years_in_Operation, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Plan_Assets, dbo.Policy_Information_Underwriting_Check_List_April.Turnover_Rate, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Turnover_Rate_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.No_Loss_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.No_Prior_Coverage_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Supp_Claim_Form_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Website_Transactional_E_Commerce_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Website_Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Transaction_E_Commerce_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Tax_Exempt_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Standard_Setting_or_Member_Certification_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Security_Precautions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Magazines_Periodicals_or_Newsletters_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Proper_Employment_Procedures_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Product_Research_or_Development_Testing_Certif_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Positive_Fund_Balance_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Peer_Review_or_Disciplinary_Action_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Merger_Acquisition_or_Consolidation_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.List_of_D_and_Os_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Employment_Application_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Employment_Application_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Disciplinary_Action_from_Peer_Review_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Disciplinary_Administrative_or_Criminal_Actions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_April.Insurance_Programs_For_Members_YN, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Last_Reporting_Year, dbo.ALL_POLICIES_12_premium_summary_April.Last_Reporting_Month, 
                      dbo.ALL_POLICIES_12_premium_summary_April.Fiscal_AY_Month_Ending, dbo.Policy_Information_ALL_POLICIES_April.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_April.DivisionName, dbo.Policy_Information_ALL_POLICIES_April.BusinessClassDesc, 
                      dbo.Policy_Information_ALL_POLICIES_April.Source_Detail_Name, dbo.Policy_Information_ALL_POLICIES_April.PIC_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_April.underwriter, dbo.Policy_Information_FF_April.FF_DO_Alt_Retention_int, 
                      dbo.Policy_Information_FF_April.FF_EPL_Alt_Retention_int, dbo.Policy_Information_FF_April.FF_EPL_Limit_int, 
                      dbo.Policy_Information_ALL_POLICIES_April.Written_Premium_Range_for_Product, dbo.Policy_Information_ALL_POLICIES_April.policyEffectivedate, 
                      dbo.Policy_Information_ALL_POLICIES_April.policyexpirationdate, dbo.Policy_Information_ALL_POLICIES_April.Latest_PY, 
                      dbo.Policy_Information_ALL_POLICIES_April.policy_effective_month, dbo.Policy_Information_ALL_POLICIES_April.policy_effective_year
HAVING      (dbo.Policy_Information_ALL_POLICIES_April.Primary_Umbrella = ''Primary'') AND 
                      (dbo.ALL_POLICIES_12_premium_summary_April.productcode = ''D&O'') AND (dbo.ALL_POLICIES_12_premium_summary_April.Fiscal_AY_Year > 2006) 
                      AND (dbo.ALL_POLICIES_12_premium_summary_April.statecode = ''CA'') AND 
                      (dbo.ALL_POLICIES_12_premium_summary_April.Coverage_Group = ''EPL'')
' 
GO
