IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Individual_Accounts_PriceMonitor_BIPD_View_1]'))
DROP VIEW [dbo].[Individual_Accounts_PriceMonitor_BIPD_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Individual_Accounts_PriceMonitor_BIPD_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.Individual_Accounts_PriceMonitor_BIPD_View_1
AS
SELECT     PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PolicyNumber, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PriorPolicyNumber, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SnapShotType, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PolicyEffectiveDate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PolicyExpirationDate, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PolicyState, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Product, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SIC, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PackageOrMonoline, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PrimaryCommissionPct, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PICCommissionPct, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.RatingModule, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.InsurableEffectiveDate, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.InsurableExpirationDate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Deductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Subline, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ClassCode, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Premium, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.InsurableID, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PriorInsurableID, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CoverageCode, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CoverageType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Territory, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Exposure, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleNumber, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.NumberOfDays, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.LimitPerDay, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleMake, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleModel, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleYear, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleCostNew, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleAge, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleDescription, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.FleetIndicator, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VehicleIdentificationNumber, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TruckType, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.StatedAmount, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.RatingBasis, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ComprehensiveFullGlassInd, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PremiumState, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.BodilyInjuryLimit1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.BodilyInjuryLimit2, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PhysicalDamageLimit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PriorInsurableIDMatchType, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PremiumOverride, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PremiumProxy, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ExposureProxy, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SourceSystemKeyValue, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.RatedVehicleNumber, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PrimaryType, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SubType, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Radius, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Usage, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.NumberOfSeats, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DualControl, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SpecialVehicle, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.GarageCity, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TerritoryZIP, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TerritoryCounty, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TerritoryCity, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TownCode, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.GarageZone, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DestinationZone, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TermFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SecondaryClassDesc, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TortLimitation, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PolicyTerm, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PremiumTerm, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.AccidentPreventionFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.AgeFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.AgreedValueFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.AntiTheftFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.AuxiliaryRunningLampFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.BaseRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.BaseRate_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.BusPassengerMedicalFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ClassFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ClassFactor_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CompulsoryBIModRate1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CompulsoryBIModRate2, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CompulsoryBIModRate3, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CostNewFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CostNewFactor_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.CSLDiscountFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DeductibleCredit, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DeductibleFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DeductibleFactor_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DumpingFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ExperienceMod, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.FinalILFFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.FleetFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.FleetFactor_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.FleetReductionFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.FullGlassDeductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.GlassDeductibleFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ILF, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ILF_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.LCM, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.LCM_Override, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate2, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate3, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate4, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate5, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate6, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate7, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate8, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ModRate9, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.MonthsFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIBaseRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIBaseRate_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIILF, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIILF_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate2, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate3, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate4, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate5, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate6, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.OptionalBIModRate7, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.Over90000Factor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PackMod, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PackMod_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PIPFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PrimaryFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageBaseRate, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageBaseRate_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageILF, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageILF_Override, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageModRate1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageModRate2, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageModRate3, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PropertyDamageModRate4, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.RMF, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SafetyCredit, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.ScheduleMod, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SecondaryFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SPCDiscount1, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SPCDiscount2, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SpecColFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SpecialCausesFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SpecialVehicleFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.SpousalLiabilityFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.StatedAmountFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.TortFactor, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.VLTWorkersFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.WaiverOfDeductible, PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.DeviationFactor, 
                      PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PrimaryFactor_Override, dbo.Policy_PATHID_Information.accountnumber, 
                      dbo.Policy_PATHID_Information.accountname, dbo.Policy_PATHID_Information.regioncode, dbo.Policy_PATHID_Information.regiondesc, 
                      dbo.Policy_PATHID_Information.PICProducer, dbo.Policy_PATHID_Information.PrimaryProducer
FROM         PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU RIGHT OUTER JOIN
                      dbo.Policy_PATHID_Information ON PriceMonitorSystem.dbo.PriceMonitorBaseDataCAU.PolicyNumber = dbo.Policy_PATHID_Information.policynumber INNER JOIN
                      dbo.Individual_Accounts_for_Reports_View_2 ON dbo.Policy_PATHID_Information.accountnumber = dbo.Individual_Accounts_for_Reports_View_2.accountnumber
' 
GO
