IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Latest_All_Lines_View_1BKOld]'))
DROP VIEW [dbo].[Latest_All_Lines_View_1BKOld]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Latest_All_Lines_View_1BKOld]'))
EXEC dbo.sp_executesql @statement = N'CREATE view [dbo].[Latest_All_Lines_View_1BKOld]
AS
SELECT     dbo.ALL_POLICIES_12_premium_summary_February.statecode, dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_February.productcode, dbo.ALL_POLICIES_12_premium_summary_February.Fiscal_AY_Year, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.currentwrittenpremium) AS currentwrittenpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.currentearnedpremium) AS currentearnedpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Policy_count_Reporting_Coverage) AS Policy_count_Reporting_Coverage, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Incurred_Loss_ALAE_with_SS_NonCat) AS Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Capped_Incurred_Loss_ALAE_with_SS_wo_cat) AS Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat) AS Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, SUM(dbo.ALL_POLICIES_12_premium_summary_February.Reported_Claims) AS Reported_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Malpractice_Count) AS COL_GLBI_Malpractice_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Malpractice_Loss) AS COL_GLBI_Malpractice_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Fraud_Breach_of_Contract_Count) AS COL_GLBI_Fraud_Breach_of_Contract_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Fraud_Breach_of_Contract_Loss) AS COL_GLBI_Fraud_Breach_of_Contract_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Injury_Count) AS COL_GLBI_Injury_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Injury_Loss) AS COL_GLBI_Injury_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Other_Count) AS COL_GLBI_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Other_Loss) AS COL_GLBI_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Sexual_Assault_Molest_Abuse_Count) AS COL_GLBI_Sexual_Assault_Molest_Abuse_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Sexual_Assault_Molest_Abuse_Loss) AS COL_GLBI_Sexual_Assault_Molest_Abuse_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_PropertyDamage_Loss) AS COL_GLBI_PropertyDamage_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_PropertyDamage_Count) AS COL_GLBI_PropertyDamage_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Theft_Loss) AS COL_GLBI_Theft_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Theft_Count) AS COL_GLBI_Theft_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_SlanderDefamtion_Loss) AS COL_GLBI_SlanderDefamtion_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_SlanderDefamtion_Count) AS COL_GLBI_SlanderDefamtion_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Discrim_WrongfulTermination_Loss) AS COL_GLBI_Discrim_WrongfulTermination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_GLBI_Discrim_WrongfulTermination_Count) AS COL_GLBI_Discrim_WrongfulTermination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Incurred_Claims) AS Incurred_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Commission_dollars) AS Commission_dollars, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Commission_Premiums) AS Commission_Premiums, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Price_Monitor_Standard_CovGrp_GL_Monitored_range, 
                      dbo.Policy_Information_ALL_POLICIES_February.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_February.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_February.Branch_Region, dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_February.Primary_Umbrella, SUM(dbo.ALL_POLICIES_12_premium_summary_February.Earned_Buildings) 
                      AS Earned_Buildings, SUM(dbo.ALL_POLICIES_12_premium_summary_February.Earned_Locations) AS Earned_Locations, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Earned_TIV) AS Earned_TIV, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.GL_Dom_Region_in_State, dbo.Policy_Information_ALL_POLICIES_February.Primary_Producer, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Policy_count_All_Cov_Combined) AS Policy_count_All_Cov_Combined, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_Working_Cover_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Policy_count_Coverage_Group) AS Policy_count_Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_February.Primary_Producer_type, dbo.Policy_Information_Underwriting_Check_List_February.Playground_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Playground_Equip_YN, dbo.Policy_Information_Underwriting_Check_List_February.Pool_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Sports_Activities_YN, dbo.Policy_Information_Underwriting_Check_List_February.Tennis_Bubble_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Tennis_Courts_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Number_of_Swimming_Pools_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Incurred_Loss_ALAE_with_SS) AS Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Capped_Incurred_Loss_ALAE_with_SS) AS Capped_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Ult_LDF_Incurred_Loss_ALAE_with_SS) AS Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS) AS Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.GL_Aggregate_Limit, dbo.Policy_Information_ALL_POLICIES_GL_February.GL_Deductible, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_Form, dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_OCC_Limit, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_Agg_Limit, dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_Form_Group, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.GL_Occurrence_Limit, dbo.Policy_Information_ALL_POLICIES_February.Endorsement_GLDX_YN, 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber, dbo.Policy_Information_ALL_POLICIES_FireAllied_February.Property_Coverage_Form, 
                      dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Form, dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Constr_Code_Dominant_NAME, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Hail_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.ZIP_Pop_Density_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Avg_Bld_Rate_Range, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Avg_Bld_Rate_rd2, dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Deductible, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Wind_Hail_Count) AS COL_Prop_Wind_Hail_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Wind_Hail_Loss) AS COL_Prop_Wind_Hail_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Water_Other_Loss) AS COL_Prop_Water_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Water_Other_Count) AS COL_Prop_Water_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Water_Sprinkler_Loss) AS COL_Prop_Water_Sprinkler_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Water_Sprinkler_Count) AS COL_Prop_Water_Sprinkler_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Theft_Van_Loss) AS COL_Prop_Theft_Van_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Theft_Van_Count) AS COL_Prop_Theft_Van_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Fire_Lightning_Explosion_Loss) AS COL_Prop_Fire_Lightning_Explosion_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Fire_Lightning_Explosion_Count) AS COL_Prop_Fire_Lightning_Explosion_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Other_Loss) AS COL_Prop_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.COL_Prop_Other_Count) AS COL_Prop_Other_Count, 
                      dbo.Policy_Information_ALL_POLICIES_February.Endorsement_Elite_YN, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Incurred_Loss_ALAE_with_SS_CatOnly) AS Incurred_Loss_ALAE_with_SS_CatOnly, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Total_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_PPT_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Buses_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Truck_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_VanPools_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OtherPublic_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Other_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_No_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_U1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_O1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_No_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_U1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_O1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Dual_Control_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Dual_Control_Percent_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.First_Policy_Year, dbo.Policy_Information_ALL_POLICIES_February.PIC_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_February.underwriter, dbo.ALL_POLICIES_12_premium_summary_February.Fiscal_AY_Month_Ending, 
                      dbo.ALL_POLICIES_12_premium_summary_February.Last_Reporting_Year, dbo.ALL_POLICIES_12_premium_summary_February.Last_Reporting_Month, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_UltLoss_Ratio, dbo.Policy_Information_ALL_POLICIES_February.Account_UltLoss_Ratio_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio, dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_NonCat_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_priorpolperiods_Range, dbo.Policy_Information_ALL_POLICIES_February.Renewals_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Branch_Office, dbo.Policy_Information_ALL_POLICIES_February.Endorsement_HS_004, 
                      Act_Pricing.dbo.DNB_Mar2011_Final.CSCORE_GMODEL8, Act_Pricing.dbo.DNB_Mar2011_Final.FSCORE_GMODEL7_1, 
                      Act_Pricing.dbo.DNB_Mar2011_Final.FSCORE_GMODEL7, Act_Pricing.dbo.DNB_Mar2011_Final.CSCORE_GMODEL7, dbo.Policy_PATHID_Information.productdesc, 
                      dbo.Policy_PATHID_Information.prodmixname, dbo.Policy_PATHID_Information.ProductTypeName, dbo.Policy_PATHID_Information.reportmixname, 
                      dbo.Policy_PATHID_Information.accountname, dbo.Policy_Information_ALL_POLICIES_February.Account_Name, dbo.Policy_PATHID_Information.CompanyCode, 
                      dbo.Policy_PATHID_Information.Product_group, dbo.Policy_PATHID_Information.NewRenewalAuto, dbo.Policy_PATHID_Information.effectiveYearMonth, 
                      dbo.Policy_PATHID_Information.effectiveYear, dbo.Policy_PATHID_Information.effectiveMonth, dbo.Policy_PATHID_Information.expirationMonth, 
                      dbo.Policy_PATHID_Information.expirationYear, dbo.Policy_PATHID_Information.expirationYearMonth, dbo.Policy_PATHID_Information.Insd_State, 
                      dbo.Policy_PATHID_Information.Insd_City, dbo.Policy_PATHID_Information.Insd_Zip, dbo.Policy_PATHID_Information.underwriterName, 
                      dbo.Policy_PATHID_Information.regiondesc, dbo.Policy_PATHID_Information.programdesc, dbo.Policy_PATHID_Information.program, 
                      dbo.Policy_PATHID_Information.Number_of_Renewals, dbo.Policy_PATHID_Information.PICProducer, dbo.Policy_PATHID_Information.PrimaryProducer, 
                      dbo.Policy_PATHID_Information.PrimaryProducerType, dbo.Policy_PATHID_Information.Account_Premium_Range, dbo.Policy_PATHID_Information.DivisionName, 
                      dbo.Policy_PATHID_Information.producttype, dbo.Policy_PATHID_Information.PrimaryProducerNumber, dbo.Policy_PATHID_Information.effectivedate, 
                      dbo.Policy_PATHID_Information.expirationdate, dbo.Policy_PATHID_Information.Insured_Years_Range, dbo.Policy_PATHID_Information.SLD_BusinessType, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_February.Incurred_Loss_ALAE_without_SS_NonCat) AS Incurred_Loss_ALAE_without_SS_NonCat, 
                      dbo.ALL_POLICIES_12_premium_summary_February.accountnumber, dbo.Policy_Information_ALL_POLICIES_February.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_February.BusinessClassDesc, dbo.ALL_POLICIES_12_premium_summary_February.COL_Breach_of_Contract_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Breach_of_Contract_Loss, dbo.ALL_POLICIES_12_premium_summary_February.COL_Discrimination_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Discrimination_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Wrongful_Termination_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Wrongful_Termination_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Harrassment_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_Harrassment_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_DO_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_DO_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_EPL_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Fiduciary_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Worplace_Violence_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_SLD_All_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_SLD_All_Other_Loss, 
                      dbo.Policy_Information_ALL_POLICIES_February.County_Pop_Density_Range, dbo.Policy_Information_Underwriting_Check_List_February.Bylaws_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Disciplinary_Administrative_or_Criminal_Actions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Disciplinary_Action_from_Peer_Review_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Employment_Application_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Employment_Application_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Financials_YN, dbo.Policy_Information_Underwriting_Check_List_February.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Information_Only_YN, dbo.Policy_Information_Underwriting_Check_List_February.List_of_D_and_Os_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Standard_Setting_or_Member_Certification_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Merger_Acquisition_or_Consolidation_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.No_Loss_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.No_Prior_Coverage_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Magazines_Periodicals_or_Newsletters_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Product_Research_or_Development_Testing_Certif_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Proper_Employment_Procedures_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Peer_Review_or_Disciplinary_Action_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Positive_Fund_Balance_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Supplemental_Claim_Form_Loss_Run_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Security_Precautions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Supp_Claim_Form_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Turnover_Rate_Range, dbo.Policy_Information_Underwriting_Check_List_February.Tax_Exempt_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Transaction_E_Commerce_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Website_Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Website_Transactional_E_Commerce_YN, dbo.ALL_POLICIES_12_premium_summary_February.acctngyear,
                       dbo.Policy_PATHID_Information.FF_Cov_ALL, dbo.Policy_PATHID_Information.PV_Cov_ALL, dbo.Policy_Information_ALL_POLICIES_February.policyEffectivedate, 
                      dbo.Policy_Information_ALL_POLICIES_February.policyexpirationdate, dbo.Policy_Information_ALL_POLICIES_February.Business_Desc, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.GLDX_Indicator, dbo.Policy_PATHID_Information.Account_ProductType_P, 
                      dbo.Policy_Information_ALL_POLICIES_February.Endorsement_CG0001, dbo.Policy_Information_ALL_POLICIES_February.Written_Premium_Range_for_Product, 
                      dbo.Policy_Information_ALL_POLICIES_February.Endorsement_HS_003, dbo.Policy_Information_ALL_POLICIES_February.Endorsement_HS_003D, 
                      dbo.Policy_Information_ALL_POLICIES_February.Written_Premium_Range, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Price_Monitor_Standard_Cov_Grp_Monitored
FROM         dbo.Policy_Information_ALL_POLICIES_FireAllied_February RIGHT OUTER JOIN
                      dbo.ALL_POLICIES_12_premium_summary_February LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February ON 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber = dbo.Policy_Information_ALL_POLICIES_AUTO_February.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_Underwriting_Check_List_February ON 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber = dbo.Policy_Information_Underwriting_Check_List_February.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_GL_AVG_RATES_February ON 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber = dbo.Policy_Information_GL_AVG_RATES_February.Policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_GL_February ON 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber = dbo.Policy_Information_ALL_POLICIES_GL_February.policynumber ON 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.policynumber = dbo.ALL_POLICIES_12_premium_summary_February.policynumber LEFT OUTER JOIN
                      dbo.Policy_PATHID_Information RIGHT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_February ON 
                      dbo.Policy_PATHID_Information.policynumber = dbo.Policy_Information_ALL_POLICIES_February.policynumber LEFT OUTER JOIN
                      Act_Pricing.dbo.DNB_Mar2011_Final ON 
                      dbo.Policy_Information_ALL_POLICIES_February.accountnumber = Act_Pricing.dbo.DNB_Mar2011_Final.ACCOUNT_NUMBER AND 
                      dbo.Policy_Information_ALL_POLICIES_February.policy_effective_year = Act_Pricing.dbo.DNB_Mar2011_Final.POLICY_YEAR ON 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber = dbo.Policy_Information_ALL_POLICIES_February.policynumber LEFT OUTER JOIN
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February ON 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.policynumber AND 
                      dbo.ALL_POLICIES_12_premium_summary_February.productcode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Productcode AND 
                      dbo.ALL_POLICIES_12_premium_summary_February.statecode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.statecode AND 
                      dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Group = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.coverage_group
GROUP BY dbo.ALL_POLICIES_12_premium_summary_February.statecode, dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_February.productcode, dbo.ALL_POLICIES_12_premium_summary_February.Fiscal_AY_Year, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Price_Monitor_Standard_CovGrp_GL_Monitored_range, 
                      dbo.Policy_Information_ALL_POLICIES_February.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_February.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_February.Branch_Region, dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_February.Primary_Umbrella, dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.GL_Dom_Region_in_State, dbo.Policy_Information_ALL_POLICIES_February.Primary_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Primary_Producer_type, dbo.Policy_Information_Underwriting_Check_List_February.Playground_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Playground_Equip_YN, dbo.Policy_Information_Underwriting_Check_List_February.Pool_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Sports_Activities_YN, dbo.Policy_Information_Underwriting_Check_List_February.Tennis_Bubble_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Tennis_Courts_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Number_of_Swimming_Pools_Range, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.GL_Aggregate_Limit, dbo.Policy_Information_ALL_POLICIES_GL_February.GL_Deductible, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_Form, dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_OCC_Limit, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_Agg_Limit, dbo.Policy_Information_ALL_POLICIES_GL_February.SAM_Form_Group, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.GL_Occurrence_Limit, dbo.Policy_Information_ALL_POLICIES_February.Endorsement_GLDX_YN, 
                      dbo.ALL_POLICIES_12_premium_summary_February.policynumber, dbo.Policy_Information_ALL_POLICIES_FireAllied_February.Property_Coverage_Form, 
                      dbo.ALL_POLICIES_12_premium_summary_February.Coverage_Form, dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Constr_Code_Dominant_NAME, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Hail_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.ZIP_Pop_Density_Dominant, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Avg_Bld_Rate_Range, 
                      dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Avg_Bld_Rate_rd2, dbo.Policy_Information_ALL_POLICIES_FireAllied_February.FA_Deductible, 
                      dbo.Policy_Information_ALL_POLICIES_February.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Total_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_PPT_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Buses_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Truck_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_VanPools_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OtherPublic_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Other_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_No_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_U1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Coll_O1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_No_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_U1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_OTC_O1000_Ded_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Dual_Control_Range, 
                      dbo.Policy_Information_ALL_POLICIES_AUTO_February.Auto_Vehicle_count_Dual_Control_Percent_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.First_Policy_Year, dbo.Policy_Information_ALL_POLICIES_February.PIC_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_February.underwriter, dbo.ALL_POLICIES_12_premium_summary_February.Fiscal_AY_Month_Ending, 
                      dbo.ALL_POLICIES_12_premium_summary_February.Last_Reporting_Year, dbo.ALL_POLICIES_12_premium_summary_February.Last_Reporting_Month, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_UltLoss_Ratio, dbo.Policy_Information_ALL_POLICIES_February.Account_UltLoss_Ratio_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio, dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_NonCat_priorpolperiods_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Account_RepLoss_Ratio_priorpolperiods_Range, dbo.Policy_Information_ALL_POLICIES_February.Renewals_Range, 
                      dbo.Policy_Information_ALL_POLICIES_February.Branch_Office, dbo.Policy_Information_ALL_POLICIES_February.Endorsement_HS_004, 
                      Act_Pricing.dbo.DNB_Mar2011_Final.CSCORE_GMODEL8, Act_Pricing.dbo.DNB_Mar2011_Final.FSCORE_GMODEL7_1, 
                      Act_Pricing.dbo.DNB_Mar2011_Final.FSCORE_GMODEL7, Act_Pricing.dbo.DNB_Mar2011_Final.CSCORE_GMODEL7, dbo.Policy_PATHID_Information.productdesc, 
                      dbo.Policy_PATHID_Information.prodmixname, dbo.Policy_PATHID_Information.ProductTypeName, dbo.Policy_PATHID_Information.reportmixname, 
                      dbo.Policy_PATHID_Information.accountname, dbo.Policy_Information_ALL_POLICIES_February.Account_Name, dbo.Policy_PATHID_Information.CompanyCode, 
                      dbo.Policy_PATHID_Information.Product_group, dbo.Policy_PATHID_Information.NewRenewalAuto, dbo.Policy_PATHID_Information.effectiveYearMonth, 
                      dbo.Policy_PATHID_Information.effectiveYear, dbo.Policy_PATHID_Information.effectiveMonth, dbo.Policy_PATHID_Information.expirationMonth, 
                      dbo.Policy_PATHID_Information.expirationYear, dbo.Policy_PATHID_Information.expirationYearMonth, dbo.Policy_PATHID_Information.Insd_State, 
                      dbo.Policy_PATHID_Information.Insd_City, dbo.Policy_PATHID_Information.Insd_Zip, dbo.Policy_PATHID_Information.underwriterName, 
                      dbo.Policy_PATHID_Information.regiondesc, dbo.Policy_PATHID_Information.programdesc, dbo.Policy_PATHID_Information.program, 
                      dbo.Policy_PATHID_Information.Number_of_Renewals, dbo.Policy_PATHID_Information.PICProducer, dbo.Policy_PATHID_Information.PrimaryProducer, 
                      dbo.Policy_PATHID_Information.PrimaryProducerType, dbo.Policy_PATHID_Information.Account_Premium_Range, dbo.Policy_PATHID_Information.DivisionName, 
                      dbo.Policy_PATHID_Information.producttype, dbo.Policy_PATHID_Information.PrimaryProducerNumber, dbo.Policy_PATHID_Information.effectivedate, 
                      dbo.Policy_PATHID_Information.expirationdate, dbo.Policy_PATHID_Information.Insured_Years_Range, dbo.Policy_PATHID_Information.SLD_BusinessType, 
                      dbo.ALL_POLICIES_12_premium_summary_February.accountnumber, dbo.Policy_Information_ALL_POLICIES_February.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_February.BusinessClassDesc, dbo.ALL_POLICIES_12_premium_summary_February.COL_Breach_of_Contract_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Breach_of_Contract_Loss, dbo.ALL_POLICIES_12_premium_summary_February.COL_Discrimination_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Discrimination_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Wrongful_Termination_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Wrongful_Termination_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Harrassment_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_Harrassment_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_DO_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_DO_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_EPL_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Fiduciary_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_Worplace_Violence_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_February.COL_SLD_All_Other_Count, dbo.ALL_POLICIES_12_premium_summary_February.COL_SLD_All_Other_Loss, 
                      dbo.Policy_Information_ALL_POLICIES_February.County_Pop_Density_Range, dbo.Policy_Information_Underwriting_Check_List_February.Bylaws_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Disciplinary_Administrative_or_Criminal_Actions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Disciplinary_Action_from_Peer_Review_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Employment_Application_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Employment_Application_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Financials_YN, dbo.Policy_Information_Underwriting_Check_List_February.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Information_Only_YN, dbo.Policy_Information_Underwriting_Check_List_February.List_of_D_and_Os_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Standard_Setting_or_Member_Certification_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Merger_Acquisition_or_Consolidation_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.No_Loss_Letter_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.No_Prior_Coverage_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Magazines_Periodicals_or_Newsletters_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Product_Research_or_Development_Testing_Certif_Services_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Proper_Employment_Procedures_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Peer_Review_or_Disciplinary_Action_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Positive_Fund_Balance_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Supplemental_Claim_Form_Loss_Run_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Security_Precautions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Supp_Claim_Form_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Turnover_Rate_Range, dbo.Policy_Information_Underwriting_Check_List_February.Tax_Exempt_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Transaction_E_Commerce_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Website_Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_February.Website_Transactional_E_Commerce_YN, dbo.ALL_POLICIES_12_premium_summary_February.acctngyear,
                       dbo.Policy_PATHID_Information.FF_Cov_ALL, dbo.Policy_PATHID_Information.PV_Cov_ALL, dbo.Policy_Information_ALL_POLICIES_February.policyEffectivedate, 
                      dbo.Policy_Information_ALL_POLICIES_February.policyexpirationdate, dbo.Policy_Information_ALL_POLICIES_February.Business_Desc, 
                      dbo.Policy_Information_ALL_POLICIES_GL_February.GLDX_Indicator, dbo.Policy_PATHID_Information.Account_ProductType_P, 
                      dbo.Policy_Information_ALL_POLICIES_February.Endorsement_CG0001, dbo.Policy_Information_ALL_POLICIES_February.Written_Premium_Range_for_Product, 
                      dbo.Policy_Information_ALL_POLICIES_February.Endorsement_HS_003, dbo.Policy_Information_ALL_POLICIES_February.Endorsement_HS_003D, 
                      dbo.Policy_Information_ALL_POLICIES_February.Written_Premium_Range, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_February.Price_Monitor_Standard_Cov_Grp_Monitored
' 
GO
