IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PVCD_All_Lines_View_1]'))
DROP VIEW [dbo].[PVCD_All_Lines_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PVCD_All_Lines_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.PVCD_All_Lines_View_1
AS
SELECT     dbo.ALL_POLICIES_12_premium_summary_May.statecode, dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_12_premium_summary_May.productcode, dbo.ALL_POLICIES_12_premium_summary_May.Fiscal_AY_Year, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.currentwrittenpremium) AS currentwrittenpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.currentearnedpremium) AS currentearnedpremium, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Policy_count_Reporting_Coverage) AS Policy_count_Reporting_Coverage, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Incurred_Loss_ALAE_with_SS_NonCat) AS Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Capped_Incurred_Loss_ALAE_with_SS_wo_cat) AS Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat) AS Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, SUM(dbo.ALL_POLICIES_12_premium_summary_May.Reported_Claims) AS Reported_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Incurred_Claims) AS Incurred_Claims, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Commission_dollars) AS Commission_dollars, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Commission_Premiums) AS Commission_Premiums, 
                      dbo.Policy_Information_ALL_POLICIES_May.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_May.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_May.Branch_Region, dbo.Policy_Information_ALL_POLICIES_May.program, 
                      dbo.Policy_Information_ALL_POLICIES_May.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_May.product_group, dbo.Policy_Information_ALL_POLICIES_May.Primary_Umbrella, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Earned_Buildings) AS Earned_Buildings, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Earned_Locations) AS Earned_Locations, SUM(dbo.ALL_POLICIES_12_premium_summary_May.Earned_TIV) 
                      AS Earned_TIV, dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.GL_Dom_Region_in_State, dbo.Policy_Information_ALL_POLICIES_May.Primary_Producer, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Policy_count_All_Cov_Combined) AS Policy_count_All_Cov_Combined, 
                      dbo.Policy_Information_ALL_POLICIES_May.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_May.Account_RepLoss_Ratio_Working_Cover_Range, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Policy_count_Coverage_Group) AS Policy_count_Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_May.accountnumber, dbo.Policy_Information_ALL_POLICIES_May.Primary_Producer_type, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Incurred_Loss_ALAE_with_SS) AS Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Capped_Incurred_Loss_ALAE_with_SS) AS Capped_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Ult_LDF_Incurred_Loss_ALAE_with_SS) AS Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS) AS Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_May.policynumber, dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Form, 
                      dbo.Policy_Information_ALL_POLICIES_May.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_May.Account_Name, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.Incurred_Loss_ALAE_with_SS_CatOnly) AS Incurred_Loss_ALAE_with_SS_CatOnly, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Handbook_YN, dbo.Policy_Information_Underwriting_Check_List_May.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Retro_Date_Applies_YN, dbo.Policy_Information_Underwriting_Check_List_May.EEO1_Report_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Subsidiaries_Affiliates_YN, dbo.Policy_Information_Underwriting_Check_List_May.Board_Experience_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Policies_YN, dbo.Policy_Information_Underwriting_Check_List_May.Claims_Past_5yrs_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Full_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Part_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Temporary_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Insider_Shareholder_Percent_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employee_Salary_GT100k_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Salary_100K_to_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Percent_of_Part_Time_and_Temp_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Plan_Assets_Range, dbo.Policy_Information_Underwriting_Check_List_May.Total_Participants_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Total_Claims_Range, dbo.Policy_Information_PVCD_May.PVCD_PVDO_Limit, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Limit, dbo.Policy_Information_PVCD_May.PVCD_PVDO_Alt_Retention, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Alt_Retention, dbo.Policy_Information_PVCD_May.PVCD_PVDO_RatingClass, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_RatingClass, dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Num_of_Employees_Range, 
                      dbo.Policy_Information_PVCD_May.PVCD_Amendment_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Partnership_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_ProPak_Elite72_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_ProPak_Elite73_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Circumstance_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Professional_Services_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Sexual_Abuse_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_BullsEye_ProPak_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Amended_Def_of_Employee_Incl_Ind_Contractors_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Amend_of_ExclusionK_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Amend_of_Severability_Provision_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Third_Party_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Punitive_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Medical_Malpractice_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Insurance_EO_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Full_Securities_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_FAILURE_TO_MAINT_INSUR_EXCLUSION_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Bankruptcy_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Shareholder_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Past_Acts_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_No_Liab_Retent_Waiver_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Delete_Consent_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Election_ERP_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Damages_Only_Retention_End_Y_N, dbo.Policy_Information_ALL_POLICIES_May.County_Pop_Density_Range, 
                      dbo.Policy_Information_ALL_POLICIES_May.Branch_Office, dbo.Policy_Information_PVCD_May.PVCD_Business_Type, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Breach_of_Contract_Loss) AS COL_Breach_of_Contract_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Discrimination_Loss) AS COL_Discrimination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Wrongful_Termination_Loss) AS COL_Wrongful_Termination_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Harrassment_Loss) AS COL_Harrassment_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_SLD_All_Other_Loss) AS COL_SLD_All_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_SLD_All_Other_Count) AS COL_SLD_All_Other_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Harrassment_Count) AS COL_Harassment_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Wrongful_Termination_Count) AS COL_WrongfulTermination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Discrimination_Count) AS COL_Discrimination_Count, 
                      SUM(dbo.ALL_POLICIES_12_premium_summary_May.COL_Breach_of_Contract_Count) AS COL_Breach_of_Contract_Count, 
                      dbo.Policy_Information_ALL_POLICIES_May.First_Policy_Year, dbo.Policy_Information_Underwriting_Check_List_May.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_DO_Other_Count, dbo.ALL_POLICIES_12_premium_summary_May.COL_DO_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_EPL_Other_Count, dbo.ALL_POLICIES_12_premium_summary_May.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Fiduciary_Other_Count, dbo.ALL_POLICIES_12_premium_summary_May.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Worplace_Violence_Other_Loss, dbo.ALL_POLICIES_12_premium_summary_May.COL_Internet_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Internet_Other_Loss, dbo.Policy_Information_PVCD_May.PVCD_PVDO_ZoneMod, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_ZoneMod, dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Num_of_Employees, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Fiscal_AY_Month_Ending, dbo.ALL_POLICIES_12_premium_summary_May.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_May.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_May.PIC_Producer, dbo.Policy_Information_ALL_POLICIES_May.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_May.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_May.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_May.DivisionName, dbo.Policy_Information_ALL_POLICIES_May.Written_Premium_Range_for_Product, 
                      dbo.Policy_Information_PVCD_May.PVCD_ZoneNum_DO, dbo.Policy_Information_PVCD_May.PVCD_ZoneNum_EPL, dbo.Policy_PATHID_Information.PICProducer, 
                      dbo.Policy_PATHID_Information.programdesc, dbo.Policy_PATHID_Information.PV_Cov_ALL, dbo.Policy_PATHID_Information.Insd_County, 
                      dbo.ALL_POLICIES_12_premium_summary_May.acctngyear, dbo.Policy_PATHID_Information.Insd_Zip, 
                      CASE WHEN isnumeric(LEFT(dbo.Policy_PATHID_Information.Insd_Zip, 3)) = 1 THEN CONVERT(float, LEFT(dbo.Policy_PATHID_Information.Insd_Zip, 3)) ELSE NULL 
                      END AS Zip3, dbo.Policy_Information_PVCD_May.PVCD_PVDO_Assets_Range, dbo.Policy_Information_PVCD_May.PVCD_Financial_Type, 
                      dbo.Policy_Information_ALL_POLICIES_May.policyEffectivedate, dbo.Policy_Information_ALL_POLICIES_May.policyexpirationdate, 
                      dbo.Policy_Information_ALL_POLICIES_May.Primary_Producer_code, dbo.Policy_Information_Underwriting_Check_List_May.Drug_Alcohol_Centers_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Engagement_Letters_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Personal_Financial_Planning_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Individual_Tax_Range, dbo.Policy_Information_Underwriting_Check_List_May.Data_Processing_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Tax_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Financial_Planning_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Compilation_Range, dbo.Policy_Information_Underwriting_Check_List_May.BookKeeping_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Audit_Range, dbo.Policy_Information_Underwriting_Check_List_May.Revenue_Gross_Billing_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Turnover_Rate_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_years_in_Operation_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Lease_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Percentage_Occupancy_Range, dbo.Policy_Information_Underwriting_Check_List_May.Locations_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Plan_Assets, dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Full_Time_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Part_Time_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Temporary_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Total_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Lease_Employees, dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Rooms, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Years_in_Operation, dbo.Policy_Information_Underwriting_Check_List_May.Audit_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Bookkeeping_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Financial_Planning_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Tax_Percent, dbo.Policy_Information_Underwriting_Check_List_May.Data_Processing_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Elder_Care_Percent, dbo.Policy_Information_Underwriting_Check_List_May.Employee_Salary_GT100k, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Individual_Tax_Percent, dbo.Policy_Information_Underwriting_Check_List_May.Physicians_On_Staff_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Management_Signoff_YN, dbo.Policy_Information_Underwriting_Check_List_May.Suits_For_Fees_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Financials_YN, dbo.Policy_Information_Underwriting_Check_List_May.For_Profit_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.State_Hospital_Institution_YN, dbo.Policy_Information_Underwriting_Check_List_May.Volunteers_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Disciplinary_Action_from_Peer_Review_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Disciplinary_Administrative_or_Criminal_Actions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Application_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Application_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.List_of_D_and_Os_YN, dbo.Policy_Information_Underwriting_Check_List_May.Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Positive_Fund_Balance_YN, dbo.Policy_PATHID_Information.regiondesc, 
                      dbo.Policy_PATHID_Information.SLD_BusinessType, 
                      CASE WHEN COL_Breach_of_Contract_Loss > 250000 THEN 250000 ELSE COL_Breach_of_Contract_Loss END AS [Capped COL_Breach_of_Contract_Loss]
FROM         dbo.Policy_Information_PVCD_May RIGHT OUTER JOIN
                      dbo.ALL_POLICIES_12_premium_summary_May ON 
                      dbo.Policy_Information_PVCD_May.policynumber = dbo.ALL_POLICIES_12_premium_summary_May.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_Underwriting_Check_List_May ON 
                      dbo.ALL_POLICIES_12_premium_summary_May.policynumber = dbo.Policy_Information_Underwriting_Check_List_May.policynumber LEFT OUTER JOIN
                      dbo.Policy_PATHID_Information RIGHT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_May ON dbo.Policy_PATHID_Information.policynumber = dbo.Policy_Information_ALL_POLICIES_May.policynumber ON 
                      dbo.ALL_POLICIES_12_premium_summary_May.policynumber = dbo.Policy_Information_ALL_POLICIES_May.policynumber LEFT OUTER JOIN
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May ON 
                      dbo.ALL_POLICIES_12_premium_summary_May.policynumber = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.policynumber AND 
                      dbo.ALL_POLICIES_12_premium_summary_May.productcode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.Productcode AND 
                      dbo.ALL_POLICIES_12_premium_summary_May.statecode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.statecode AND 
                      dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Group = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.coverage_group
GROUP BY dbo.ALL_POLICIES_12_premium_summary_May.statecode, dbo.ALL_POLICIES_12_premium_summary_May.policynumber, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Reporting_group, dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Form, 
                      dbo.ALL_POLICIES_12_premium_summary_May.productcode, dbo.ALL_POLICIES_12_premium_summary_May.Fiscal_AY_Year, 
                      dbo.Policy_Information_ALL_POLICIES_May.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_May.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_May.Branch_Region, dbo.Policy_Information_ALL_POLICIES_May.program, 
                      dbo.Policy_Information_ALL_POLICIES_May.Written_Premium_Range, dbo.ALL_POLICIES_12_premium_summary_May.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_May.product_group, dbo.Policy_Information_ALL_POLICIES_May.Primary_Umbrella, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.GL_Dom_Region_in_State, dbo.Policy_Information_ALL_POLICIES_May.Primary_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_May.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_May.Account_RepLoss_Ratio_Working_Cover_Range, dbo.Policy_Information_ALL_POLICIES_May.accountnumber, 
                      dbo.Policy_Information_ALL_POLICIES_May.Primary_Producer_type, dbo.Policy_Information_ALL_POLICIES_May.Endorsement_Elite_YN, 
                      dbo.Policy_Information_ALL_POLICIES_May.Account_Name, dbo.Policy_Information_Underwriting_Check_List_May.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Form_5500_YN, dbo.Policy_Information_Underwriting_Check_List_May.Retro_Date_Applies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.EEO1_Report_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Subsidiaries_Affiliates_YN, dbo.Policy_Information_Underwriting_Check_List_May.Board_Experience_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Policies_YN, dbo.Policy_Information_Underwriting_Check_List_May.Claims_Past_5yrs_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Full_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Part_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Temporary_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Insider_Shareholder_Percent_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employee_Salary_GT100k_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Salary_100K_to_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Percent_of_Part_Time_and_Temp_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Plan_Assets_Range, dbo.Policy_Information_Underwriting_Check_List_May.Total_Participants_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Total_Claims_Range, dbo.Policy_Information_PVCD_May.PVCD_PVDO_Limit, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Limit, dbo.Policy_Information_PVCD_May.PVCD_PVDO_Alt_Retention, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Alt_Retention, dbo.Policy_Information_PVCD_May.PVCD_PVDO_RatingClass, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_RatingClass, dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Num_of_Employees_Range, 
                      dbo.Policy_Information_PVCD_May.PVCD_Amendment_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Partnership_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_ProPak_Elite72_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_ProPak_Elite73_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Circumstance_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Professional_Services_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Sexual_Abuse_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_BullsEye_ProPak_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Amended_Def_of_Employee_Incl_Ind_Contractors_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Amend_of_ExclusionK_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Amend_of_Severability_Provision_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Third_Party_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Punitive_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Medical_Malpractice_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Insurance_EO_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Full_Securities_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_FAILURE_TO_MAINT_INSUR_EXCLUSION_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Bankruptcy_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Shareholder_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Past_Acts_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_No_Liab_Retent_Waiver_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Delete_Consent_End_Y_N, dbo.Policy_Information_PVCD_May.PVCD_Election_ERP_End_Y_N, 
                      dbo.Policy_Information_PVCD_May.PVCD_Damages_Only_Retention_End_Y_N, dbo.Policy_Information_PVCD_May.New_Renew_Tail, 
                      dbo.Policy_Information_PVCD_May.Renew_New_Auto, dbo.Policy_Information_PVCD_May.Branch_Region, 
                      dbo.Policy_Information_ALL_POLICIES_May.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_May.Branch_Office, 
                      dbo.Policy_Information_PVCD_May.PVCD_Business_Type, dbo.ALL_POLICIES_12_premium_summary_May.Incurred_Loss_ALAE_with_SS_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_May.First_Policy_Year, dbo.ALL_POLICIES_12_premium_summary_May.Capped_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, dbo.ALL_POLICIES_12_premium_summary_May.Incurred_Claims, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_May.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.ALL_POLICIES_12_premium_summary_May.experienceproduct, dbo.ALL_POLICIES_12_premium_summary_May.COL_DO_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_DO_Other_Loss, dbo.ALL_POLICIES_12_premium_summary_May.COL_EPL_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_EPL_Other_Loss, dbo.ALL_POLICIES_12_premium_summary_May.COL_Fiduciary_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Fiduciary_Other_Loss, dbo.ALL_POLICIES_12_premium_summary_May.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Worplace_Violence_Other_Loss, dbo.ALL_POLICIES_12_premium_summary_May.COL_Internet_Other_Count, 
                      dbo.ALL_POLICIES_12_premium_summary_May.COL_Internet_Other_Loss, dbo.Policy_Information_PVCD_May.PVCD_PVDO_ZoneMod, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVEPL_ZoneMod, dbo.Policy_Information_PVCD_May.PVCD_PVEPL_Num_of_Employees, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Fiscal_AY_Month_Ending, dbo.ALL_POLICIES_12_premium_summary_May.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_12_premium_summary_May.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_May.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_May.PIC_Producer, dbo.Policy_Information_ALL_POLICIES_May.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_May.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_May.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_May.DivisionName, dbo.Policy_Information_PVCD_May.PVCD_ZoneNum_EPL, 
                      dbo.Policy_Information_PVCD_May.PVCD_ZoneNum_DO, dbo.Policy_Information_PVCD_May.PVCD_ZipCode_DO, 
                      dbo.Policy_Information_PVCD_May.PVCD_ZipCode_EPL, dbo.Policy_Information_PVCD_May.PVCD_State_DO, dbo.Policy_Information_PVCD_May.PVCD_State_EPL, 
                      dbo.Policy_Information_ALL_POLICIES_May.Written_Premium_Range_for_Product, dbo.Policy_PATHID_Information.PICProducer, 
                      dbo.Policy_PATHID_Information.programdesc, dbo.Policy_PATHID_Information.PV_Cov_ALL, dbo.Policy_PATHID_Information.Insd_County, 
                      dbo.ALL_POLICIES_12_premium_summary_May.acctngyear, dbo.Policy_PATHID_Information.Insd_Zip, 
                      dbo.Policy_Information_PVCD_May.PVCD_PVDO_Assets_Range, dbo.Policy_Information_PVCD_May.PVCD_Financial_Type, 
                      dbo.Policy_Information_ALL_POLICIES_May.policyEffectivedate, dbo.Policy_Information_ALL_POLICIES_May.policyexpirationdate, 
                      dbo.Policy_Information_ALL_POLICIES_May.Primary_Producer_code, dbo.Policy_Information_Underwriting_Check_List_May.Drug_Alcohol_Centers_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Engagement_Letters_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Personal_Financial_Planning_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Individual_Tax_Range, dbo.Policy_Information_Underwriting_Check_List_May.Data_Processing_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Tax_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Financial_Planning_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Compilation_Range, dbo.Policy_Information_Underwriting_Check_List_May.BookKeeping_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Audit_Range, dbo.Policy_Information_Underwriting_Check_List_May.Revenue_Gross_Billing_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Turnover_Rate_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_years_in_Operation_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Lease_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Percentage_Occupancy_Range, dbo.Policy_Information_Underwriting_Check_List_May.Locations_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Plan_Assets, dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Full_Time_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Part_Time_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Temporary_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Total_Employees, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Lease_Employees, dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Rooms, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Number_of_Years_in_Operation, dbo.Policy_Information_Underwriting_Check_List_May.Audit_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Bookkeeping_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Financial_Planning_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Corporate_Tax_Percent, dbo.Policy_Information_Underwriting_Check_List_May.Data_Processing_Percent, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Elder_Care_Percent, dbo.Policy_Information_Underwriting_Check_List_May.Employee_Salary_GT100k, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Individual_Tax_Percent, dbo.Policy_Information_Underwriting_Check_List_May.Physicians_On_Staff_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Management_Signoff_YN, dbo.Policy_Information_Underwriting_Check_List_May.Suits_For_Fees_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Financials_YN, dbo.Policy_Information_Underwriting_Check_List_May.For_Profit_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.State_Hospital_Institution_YN, dbo.Policy_Information_Underwriting_Check_List_May.Volunteers_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Disciplinary_Action_from_Peer_Review_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Disciplinary_Administrative_or_Criminal_Actions_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Application_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Employment_Application_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.List_of_D_and_Os_YN, dbo.Policy_Information_Underwriting_Check_List_May.Information_Only_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_May.Positive_Fund_Balance_YN, dbo.Policy_PATHID_Information.regiondesc, 
                      dbo.Policy_PATHID_Information.SLD_BusinessType, 
                      CASE WHEN COL_Breach_of_Contract_Loss > 250000 THEN 250000 ELSE COL_Breach_of_Contract_Loss END
HAVING      (dbo.ALL_POLICIES_12_premium_summary_May.Fiscal_AY_Year > 2008) AND (dbo.ALL_POLICIES_12_premium_summary_May.productcode = ''pv'') AND 
                      (NOT (dbo.ALL_POLICIES_12_premium_summary_May.statecode IN (''NY'', ''CA'')))
' 
GO
