IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PVCD_All_Lines_15Month_View_1]'))
DROP VIEW [dbo].[PVCD_All_Lines_15Month_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[PVCD_All_Lines_15Month_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.PVCD_All_Lines_15Month_View_1
AS
SELECT     dbo.ALL_POLICIES_15_premium_summary_March.statecode, dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Reporting_group, 
                      dbo.ALL_POLICIES_15_premium_summary_March.productcode, dbo.ALL_POLICIES_15_premium_summary_March.Fiscal_AY_Year, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.currentwrittenpremium) AS currentwrittenpremium, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.currentearnedpremium) AS currentearnedpremium, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Policy_count_Reporting_Coverage) AS Policy_count_Reporting_Coverage, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Incurred_Loss_ALAE_with_SS_NonCat) AS Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat) 
                      AS Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat) 
                      AS Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, SUM(dbo.ALL_POLICIES_15_premium_summary_March.Reported_Claims) 
                      AS Reported_Claims, SUM(dbo.ALL_POLICIES_15_premium_summary_March.Incurred_Claims) AS Incurred_Claims, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Commission_dollars) AS Commission_dollars, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Commission_Premiums) AS Commission_Premiums, 
                      dbo.Policy_Information_ALL_POLICIES_March.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_March.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_March.Branch_Region, dbo.Policy_Information_ALL_POLICIES_March.program, 
                      dbo.Policy_Information_ALL_POLICIES_March.Written_Premium_Range, dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_March.product_group, dbo.Policy_Information_ALL_POLICIES_March.Primary_Umbrella, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Earned_Buildings) AS Earned_Buildings, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Earned_Locations) AS Earned_Locations, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Earned_TIV) AS Earned_TIV, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_March.Primary_Producer, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Policy_count_All_Cov_Combined) AS Policy_count_All_Cov_Combined, 
                      dbo.Policy_Information_ALL_POLICIES_March.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_March.Account_RepLoss_Ratio_Working_Cover_Range, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Policy_count_Coverage_Group) AS Policy_count_Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_March.accountnumber, dbo.Policy_Information_ALL_POLICIES_March.Primary_Producer_type, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Incurred_Loss_ALAE_with_SS) AS Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Capped_Incurred_Loss_ALAE_with_SS) AS Capped_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Ult_LDF_Incurred_Loss_ALAE_with_SS) AS Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS) AS Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_15_premium_summary_March.policynumber, dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Form, 
                      dbo.Policy_Information_ALL_POLICIES_March.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_March.Account_Name, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.Incurred_Loss_ALAE_with_SS_CatOnly) AS Incurred_Loss_ALAE_with_SS_CatOnly, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Retro_Date_Applies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.EEO1_Report_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Board_Experience_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Employment_Policies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Claims_Past_5yrs_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Full_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Part_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Temporary_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Insider_Shareholder_Percent_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Employee_Salary_GT100k_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Salary_100K_to_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Percent_of_Part_Time_and_Temp_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Total_Participants_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Total_Claims_Range, dbo.Policy_Information_PVCD_March.PVCD_PVDO_Limit, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Limit, dbo.Policy_Information_PVCD_March.PVCD_PVDO_Alt_Retention, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Alt_Retention, dbo.Policy_Information_PVCD_March.PVCD_PVDO_RatingClass, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_RatingClass, dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Num_of_Employees_Range, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amendment_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_Partnership_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_ProPak_Elite72_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_ProPak_Elite73_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Circumstance_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Professional_Services_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Sexual_Abuse_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_BullsEye_ProPak_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amended_Def_of_Employee_Incl_Ind_Contractors_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amend_of_ExclusionK_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amend_of_Severability_Provision_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Third_Party_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Punitive_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Medical_Malpractice_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Insurance_EO_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Full_Securities_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_FAILURE_TO_MAINT_INSUR_EXCLUSION_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Bankruptcy_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_Shareholder_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Past_Acts_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_No_Liab_Retent_Waiver_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Delete_Consent_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_Election_ERP_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Damages_Only_Retention_End_Y_N, 
                      dbo.Policy_Information_ALL_POLICIES_March.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_March.Branch_Office, 
                      dbo.Policy_Information_PVCD_March.PVCD_Business_Type, SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Breach_of_Contract_Loss) 
                      AS COL_Breach_of_Contract_Loss, SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Discrimination_Loss) AS COL_Discrimination_Loss, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Wrongful_Termination_Loss) AS COL_Wrongful_Termination_Loss, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Harrassment_Loss) AS COL_Harrassment_Loss, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_SLD_All_Other_Loss) AS COL_SLD_All_Other_Loss, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_SLD_All_Other_Count) AS COL_SLD_All_Other_Count, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Harrassment_Count) AS COL_Harassment_Count, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Wrongful_Termination_Count) AS COL_WrongfulTermination_Count, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Discrimination_Count) AS COL_Discrimination_Count, 
                      SUM(dbo.ALL_POLICIES_15_premium_summary_March.COL_Breach_of_Contract_Count) AS COL_Breach_of_Contract_Count, 
                      dbo.Policy_Information_ALL_POLICIES_March.First_Policy_Year, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_DO_Other_Loss, dbo.ALL_POLICIES_15_premium_summary_March.COL_EPL_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Fiduciary_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Worplace_Violence_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Internet_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Internet_Other_Loss, dbo.Policy_Information_PVCD_March.PVCD_PVDO_ZoneMod, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_ZoneMod, dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Num_of_Employees, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Fiscal_AY_Month_Ending, dbo.ALL_POLICIES_15_premium_summary_March.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_March.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_March.PIC_Producer, dbo.Policy_Information_ALL_POLICIES_March.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_March.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_March.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_March.DivisionName, dbo.Policy_Information_ALL_POLICIES_March.Written_Premium_Range_for_Product, 
                      dbo.Policy_Information_PVCD_March.PVCD_ZoneNum_DO, dbo.Policy_Information_PVCD_March.PVCD_ZoneNum_EPL, 
                      dbo.Policy_PATHID_Information.PICProducer, dbo.Policy_PATHID_Information.programdesc, dbo.Policy_PATHID_Information.PV_Cov_ALL, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Breach_of_Contract_Count AS COL_Breach_of_Contract_Count1, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Breach_of_Contract_Loss AS ASCOL_Breach_of_Contract_Loss1, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Discrimination_Count AS COL_Discrimination_Count1, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Discrimination_Loss AS COL_Discrimination_Loss1, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Wrongful_Termination_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Wrongful_Termination_Loss AS COL_Wrongful_Termination_Loss1, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Harrassment_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Harrassment_Loss AS COL_Harrassment_Loss1, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_DO_Other_Count, dbo.ALL_POLICIES_15_premium_summary_March.acctngyear, 
                      dbo.Policy_PATHID_Information.Insd_County, dbo.Policy_PATHID_Information.Insd_Zip
FROM         dbo.Policy_PATHID_Information RIGHT OUTER JOIN
                      dbo.Policy_Information_ALL_POLICIES_March ON 
                      dbo.Policy_PATHID_Information.policynumber = dbo.Policy_Information_ALL_POLICIES_March.policynumber RIGHT OUTER JOIN
                      dbo.ALL_POLICIES_15_premium_summary_March LEFT OUTER JOIN
                      dbo.Policy_Information_PVCD_March ON 
                      dbo.ALL_POLICIES_15_premium_summary_March.policynumber = dbo.Policy_Information_PVCD_March.policynumber LEFT OUTER JOIN
                      dbo.Policy_Information_Underwriting_Check_List_March ON 
                      dbo.ALL_POLICIES_15_premium_summary_March.policynumber = dbo.Policy_Information_Underwriting_Check_List_March.policynumber ON 
                      dbo.Policy_Information_ALL_POLICIES_March.policynumber = dbo.ALL_POLICIES_15_premium_summary_March.policynumber LEFT OUTER JOIN
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March ON 
                      dbo.ALL_POLICIES_15_premium_summary_March.policynumber = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.policynumber AND
                       dbo.ALL_POLICIES_15_premium_summary_March.productcode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.Productcode AND 
                      dbo.ALL_POLICIES_15_premium_summary_March.statecode = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.statecode AND 
                      dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Group = dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.coverage_group
GROUP BY dbo.ALL_POLICIES_15_premium_summary_March.statecode, dbo.ALL_POLICIES_15_premium_summary_March.policynumber, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Reporting_group, dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Form, 
                      dbo.ALL_POLICIES_15_premium_summary_March.productcode, dbo.ALL_POLICIES_15_premium_summary_March.Fiscal_AY_Year, 
                      dbo.Policy_Information_ALL_POLICIES_March.New_Renew_Tail, dbo.Policy_Information_ALL_POLICIES_March.Renew_New_Auto, 
                      dbo.Policy_Information_ALL_POLICIES_March.Branch_Region, dbo.Policy_Information_ALL_POLICIES_March.program, 
                      dbo.Policy_Information_ALL_POLICIES_March.Written_Premium_Range, dbo.ALL_POLICIES_15_premium_summary_March.Coverage_Group, 
                      dbo.Policy_Information_ALL_POLICIES_March.product_group, dbo.Policy_Information_ALL_POLICIES_March.Primary_Umbrella, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.GL_Dom_Terr_Description, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.GL_Dom_Region_in_State, 
                      dbo.Policy_Information_ALL_POLICIES_March.Primary_Producer, 
                      dbo.Policy_Information_ALL_POLICIES_March.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_March.Account_RepLoss_Ratio_Working_Cover_Range, 
                      dbo.Policy_Information_ALL_POLICIES_March.accountnumber, dbo.Policy_Information_ALL_POLICIES_March.Primary_Producer_type, 
                      dbo.Policy_Information_ALL_POLICIES_March.Endorsement_Elite_YN, dbo.Policy_Information_ALL_POLICIES_March.Account_Name, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Employment_Handbook_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Form_5500_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Retro_Date_Applies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.EEO1_Report_Received_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Subsidiaries_Affiliates_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Board_Experience_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Employment_Policies_YN, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Claims_Past_5yrs_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Full_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Part_Time_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Temporary_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Number_of_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Insider_Shareholder_Percent_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Employee_Salary_GT100k_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Salary_100K_to_Total_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Percent_of_Part_Time_and_Temp_Employees_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Plan_Assets_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Total_Participants_Range, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Total_Claims_Range, dbo.Policy_Information_PVCD_March.PVCD_PVDO_Limit, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Limit, dbo.Policy_Information_PVCD_March.PVCD_PVDO_Alt_Retention, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Alt_Retention, dbo.Policy_Information_PVCD_March.PVCD_PVDO_RatingClass, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_RatingClass, dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Num_of_Employees_Range, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amendment_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_Partnership_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_ProPak_Elite72_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_ProPak_Elite73_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Circumstance_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Professional_Services_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Sexual_Abuse_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_BullsEye_ProPak_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amended_Def_of_Employee_Incl_Ind_Contractors_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amend_of_ExclusionK_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Amend_of_Severability_Provision_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Third_Party_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Punitive_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Medical_Malpractice_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Insurance_EO_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Full_Securities_Exclusion_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_FAILURE_TO_MAINT_INSUR_EXCLUSION_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Bankruptcy_Exclusion_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_Shareholder_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Past_Acts_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_No_Liab_Retent_Waiver_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Delete_Consent_End_Y_N, dbo.Policy_Information_PVCD_March.PVCD_Election_ERP_End_Y_N, 
                      dbo.Policy_Information_PVCD_March.PVCD_Damages_Only_Retention_End_Y_N, dbo.Policy_Information_PVCD_March.New_Renew_Tail, 
                      dbo.Policy_Information_PVCD_March.Renew_New_Auto, dbo.Policy_Information_PVCD_March.Branch_Region, 
                      dbo.Policy_Information_ALL_POLICIES_March.County_Pop_Density_Range, dbo.Policy_Information_ALL_POLICIES_March.Branch_Office, 
                      dbo.Policy_Information_PVCD_March.PVCD_Business_Type, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Incurred_Loss_ALAE_with_SS_NonCat, 
                      dbo.Policy_Information_ALL_POLICIES_March.First_Policy_Year, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Capped_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Incurred_Claims, 
                      dbo.Policy_Information_Underwriting_Check_List_March.Clean_Warranty_Letter_Received_YN, 
                      dbo.Policy_Product_State_Coverage_Data_ALL_POLICIES_March.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.ALL_POLICIES_15_premium_summary_March.experienceproduct, dbo.ALL_POLICIES_15_premium_summary_March.COL_DO_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_EPL_Other_Count, dbo.ALL_POLICIES_15_premium_summary_March.COL_EPL_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Fiduciary_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Fiduciary_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Worplace_Violence_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Worplace_Violence_Other_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Internet_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Internet_Other_Loss, dbo.Policy_Information_PVCD_March.PVCD_PVDO_ZoneMod, 
                      dbo.Policy_Information_PVCD_March.PVCD_PVEPL_ZoneMod, dbo.Policy_Information_PVCD_March.PVCD_PVEPL_Num_of_Employees, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Fiscal_AY_Month_Ending, dbo.ALL_POLICIES_15_premium_summary_March.Last_Reporting_Year, 
                      dbo.ALL_POLICIES_15_premium_summary_March.Last_Reporting_Month, dbo.Policy_Information_ALL_POLICIES_March.underwriter, 
                      dbo.Policy_Information_ALL_POLICIES_March.PIC_Producer, dbo.Policy_Information_ALL_POLICIES_March.Source_Detail_Name, 
                      dbo.Policy_Information_ALL_POLICIES_March.BusinessClassDesc, dbo.Policy_Information_ALL_POLICIES_March.ProductType, 
                      dbo.Policy_Information_ALL_POLICIES_March.DivisionName, dbo.Policy_Information_PVCD_March.PVCD_ZoneNum_EPL, 
                      dbo.Policy_Information_PVCD_March.PVCD_ZoneNum_DO, dbo.Policy_Information_PVCD_March.PVCD_ZipCode_DO, 
                      dbo.Policy_Information_PVCD_March.PVCD_ZipCode_EPL, dbo.Policy_Information_PVCD_March.PVCD_State_DO, 
                      dbo.Policy_Information_PVCD_March.PVCD_State_EPL, dbo.Policy_Information_ALL_POLICIES_March.Written_Premium_Range_for_Product, 
                      dbo.Policy_PATHID_Information.PICProducer, dbo.Policy_PATHID_Information.programdesc, dbo.Policy_PATHID_Information.PV_Cov_ALL, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Breach_of_Contract_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Breach_of_Contract_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Discrimination_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Discrimination_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Wrongful_Termination_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Wrongful_Termination_Loss, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Harrassment_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.COL_Harrassment_Loss, dbo.ALL_POLICIES_15_premium_summary_March.COL_DO_Other_Count, 
                      dbo.ALL_POLICIES_15_premium_summary_March.acctngyear, dbo.Policy_PATHID_Information.Insd_County, 
                      dbo.Policy_PATHID_Information.Insd_Zip
HAVING      (dbo.ALL_POLICIES_15_premium_summary_March.productcode = ''PV'') AND 
                      (dbo.ALL_POLICIES_15_premium_summary_March.Fiscal_AY_Year > ''2005'')
' 
GO
