IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[HC_All_Lines_View_1_Oct]'))
DROP VIEW [dbo].[HC_All_Lines_View_1_Oct]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[HC_All_Lines_View_1_Oct]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW dbo.HC_All_Lines_View_1_Oct
AS
SELECT     dbo.Latest_All_Lines_View_1_Oct.statecode, dbo.Latest_All_Lines_View_1_Oct.Coverage_Reporting_group, 
                      dbo.Latest_All_Lines_View_1_Oct.productcode, dbo.Latest_All_Lines_View_1_Oct.Fiscal_AY_Year, 
                      dbo.Latest_All_Lines_View_1_Oct.currentwrittenpremium, dbo.Latest_All_Lines_View_1_Oct.currentearnedpremium, 
                      dbo.Latest_All_Lines_View_1_Oct.Policy_count_Reporting_Coverage, dbo.Latest_All_Lines_View_1_Oct.Incurred_Loss_ALAE_with_SS_NonCat, 
                      dbo.Latest_All_Lines_View_1_Oct.Capped_Incurred_Loss_ALAE_with_SS_wo_cat, 
                      dbo.Latest_All_Lines_View_1_Oct.Ult_LDF_Incurred_Loss_ALAE_with_SS_NonCat, 
                      dbo.Latest_All_Lines_View_1_Oct.Ult_LDF_Capped_Incurred_Loss_ALAE_with_SS_wo_cat, dbo.Latest_All_Lines_View_1_Oct.Reported_Claims, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Malpractice_Count, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Malpractice_Loss, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Fraud_Breach_of_Contract_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Fraud_Breach_of_Contract_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Injury_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Injury_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Other_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Other_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Sexual_Assault_Molest_Abuse_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Sexual_Assault_Molest_Abuse_Loss, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_PropertyDamage_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_PropertyDamage_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Theft_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Theft_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_SlanderDefamtion_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_SlanderDefamtion_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Discrim_WrongfulTermination_Loss, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_GLBI_Discrim_WrongfulTermination_Count, dbo.Latest_All_Lines_View_1_Oct.Incurred_Claims, 
                      dbo.Latest_All_Lines_View_1_Oct.Commission_dollars, dbo.Latest_All_Lines_View_1_Oct.Commission_Premiums, 
                      dbo.Latest_All_Lines_View_1_Oct.Price_Monitor_Standard_CovGrp_GL_Monitored_range, dbo.Latest_All_Lines_View_1_Oct.New_Renew_Tail, 
                      dbo.Latest_All_Lines_View_1_Oct.Renew_New_Auto, dbo.Latest_All_Lines_View_1_Oct.Branch_Region, dbo.Latest_All_Lines_View_1_Oct.program, 
                      dbo.Latest_All_Lines_View_1_Oct.Written_Premium_Range, dbo.Latest_All_Lines_View_1_Oct.Coverage_Group, 
                      dbo.Latest_All_Lines_View_1_Oct.Product_group, dbo.Latest_All_Lines_View_1_Oct.Primary_Umbrella, 
                      dbo.Latest_All_Lines_View_1_Oct.Earned_Buildings, dbo.Latest_All_Lines_View_1_Oct.Earned_Locations, 
                      dbo.Latest_All_Lines_View_1_Oct.Earned_TIV, dbo.Latest_All_Lines_View_1_Oct.GL_Dom_Terr_Description, 
                      dbo.Latest_All_Lines_View_1_Oct.GL_Dom_Region_in_State, dbo.Latest_All_Lines_View_1_Oct.Primary_Producer, 
                      dbo.Latest_All_Lines_View_1_Oct.Policy_count_All_Cov_Combined, dbo.Latest_All_Lines_View_1_Oct.Account_UltLoss_Ratio_Working_Cover_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Account_RepLoss_Ratio_Working_Cover_Range, dbo.Latest_All_Lines_View_1_Oct.Policy_count_Coverage_Group, 
                      dbo.Latest_All_Lines_View_1_Oct.accountnumber, dbo.Latest_All_Lines_View_1_Oct.Primary_Producer_type, 
                      dbo.Latest_All_Lines_View_1_Oct.Playground_YN, dbo.Latest_All_Lines_View_1_Oct.Playground_Equip_YN, 
                      dbo.Latest_All_Lines_View_1_Oct.Pool_YN, dbo.Latest_All_Lines_View_1_Oct.Sports_Activities_YN, 
                      dbo.Latest_All_Lines_View_1_Oct.Tennis_Bubble_YN, dbo.Latest_All_Lines_View_1_Oct.Tennis_Courts_YN, 
                      dbo.Latest_All_Lines_View_1_Oct.Number_of_Swimming_Pools_Range, dbo.Latest_All_Lines_View_1_Oct.Incurred_Loss_ALAE_with_SS, 
                      dbo.Latest_All_Lines_View_1_Oct.Capped_Incurred_Loss_ALAE_with_SS, dbo.Latest_All_Lines_View_1_Oct.Ult_LDF_Incurred_Loss_ALAE_with_SS, 
                      dbo.Latest_All_Lines_View_1_Oct.Ult_LDF_Capped_Inc_Loss_ALAE_with_SS, dbo.Latest_All_Lines_View_1_Oct.GL_Aggregate_Limit, 
                      dbo.Latest_All_Lines_View_1_Oct.GL_Deductible, dbo.Latest_All_Lines_View_1_Oct.GLDX_Indicator, dbo.Latest_All_Lines_View_1_Oct.SAM_Form, 
                      dbo.Latest_All_Lines_View_1_Oct.SAM_OCC_Limit, dbo.Latest_All_Lines_View_1_Oct.SAM_Agg_Limit, 
                      dbo.Latest_All_Lines_View_1_Oct.SAM_Form_Group, dbo.Latest_All_Lines_View_1_Oct.GL_Occurrence_Limit, 
                      dbo.Latest_All_Lines_View_1_Oct.Endorsement_GLDX_YN, dbo.Latest_All_Lines_View_1_Oct.policynumber, 
                      dbo.Latest_All_Lines_View_1_Oct.Property_Coverage_Form, dbo.Latest_All_Lines_View_1_Oct.Coverage_Form, 
                      dbo.Latest_All_Lines_View_1_Oct.FA_Constr_Code_Dominant_NAME, dbo.Latest_All_Lines_View_1_Oct.FA_Hail_Dominant, 
                      dbo.Latest_All_Lines_View_1_Oct.ZIP_Pop_Density_Dominant, dbo.Latest_All_Lines_View_1_Oct.FA_Avg_Bld_Rate_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.FA_Avg_Bld_Rate_rd2, dbo.Latest_All_Lines_View_1_Oct.FA_Deductible, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Wind_Hail_Count, dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Wind_Hail_Loss, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Water_Other_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Water_Other_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Water_Sprinkler_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Water_Sprinkler_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Theft_Van_Loss, dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Theft_Van_Count, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Fire_Lightning_Explosion_Loss, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Fire_Lightning_Explosion_Count, dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Other_Loss, 
                      dbo.Latest_All_Lines_View_1_Oct.COL_Prop_Other_Count, dbo.Latest_All_Lines_View_1_Oct.Endorsement_Elite_YN, 
                      dbo.Latest_All_Lines_View_1_Oct.Account_Name, dbo.Latest_All_Lines_View_1_Oct.Incurred_Loss_ALAE_with_SS_CatOnly, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Total_Range, dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_PPT_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Buses_Range, dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Truck_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_VanPools_Range, dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_OtherPublic_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Other_Range, dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Coll_No_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Coll_U1000_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Coll_1000_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Coll_O1000_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_OTC_No_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_OTC_U1000_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_OTC_1000_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_OTC_O1000_Ded_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Dual_Control_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.Auto_Vehicle_count_Dual_Control_Percent_Range, dbo.Latest_All_Lines_View_1_Oct.BusinessClassDesc, 
                      dbo.Latest_All_Lines_View_1_Oct.DivisionName, dbo.Latest_All_Lines_View_1_Oct.producttype, 
                      dbo.Latest_All_Lines_View_1_Oct.Source_Detail_Name, dbo.Latest_All_Lines_View_1_Oct.First_Policy_Year, 
                      dbo.Latest_All_Lines_View_1_Oct.PIC_Producer, dbo.Latest_All_Lines_View_1_Oct.underwriter, 
                      dbo.Latest_All_Lines_View_1_Oct.Fiscal_AY_Month_Ending, dbo.Latest_All_Lines_View_1_Oct.Last_Reporting_Year, 
                      dbo.Latest_All_Lines_View_1_Oct.Last_Reporting_Month, dbo.Latest_All_Lines_View_1_Oct.Price_Monitor_Standard_Cov_Grp_Monitored_range, 
                      dbo.Latest_All_Lines_View_1_Oct.Account_UltLoss_Ratio, dbo.Latest_All_Lines_View_1_Oct.Account_UltLoss_Ratio_NonCat, 
                      dbo.Latest_All_Lines_View_1_Oct.Account_RepLoss_Ratio, dbo.Latest_All_Lines_View_1_Oct.Account_RepLoss_Ratio_NonCat, 
                      dbo.Latest_All_Lines_View_1_Oct.CompanyCode, dbo.Latest_All_Lines_View_1_Oct.Number_of_Renewals, 
                      dbo.Latest_All_Lines_View_1_Oct.Renewals_Range, dbo.Policy_Information_GL_AVG_RATES_October.Sales_Service_Orgs_Avg_Rate_Range, 
                      dbo.Policy_Information_GL_AVG_RATES_October.Sales_Service_Orgs_Avg_Rate, 
                      dbo.Policy_Information_GL_AVG_RATES_October.Sales_Service_Orgs_Exposure_Adj, 
                      dbo.Policy_Information_GL_AVG_RATES_October.Sales_Service_Orgs_Exposure, 
                      dbo.Policy_Information_GL_AVG_RATES_October.Sales_Service_Orgs_Premium, 
                      dbo.Policy_Information_GL_AVG_RATES_October.Sales_Service_Orgs_Class_Group, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCare_Premium, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCare_Exposure, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCare_Exposure_Adj, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCare_Avg_Rate, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCare_Avg_Rate_Range, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareNonSales_Premium, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareNonSales_Exposure, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareNonSales_Exposure_Adj, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareNonSales_Avg_Rate, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareNonSales_Avg_Rate_Range, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareSales_Premium, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareSales_Exposure, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareSales_Exposure_Adj, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareSales_Avg_Rate, 
                      dbo.Policy_Information_GL_AVG_RATES_October.HomeHealthCareSales_Avg_Rate_Range, dbo.Latest_All_Lines_View_1_Oct.Endorsement_HS_004, 
                      dbo.Latest_All_Lines_View_1_Oct.reportmixname, dbo.Latest_All_Lines_View_1_Oct.Account_Premium_Range, 
                      dbo.Latest_All_Lines_View_1_Oct.programdesc, dbo.Latest_All_Lines_View_1_Oct.PICProducer, dbo.Latest_All_Lines_View_1_Oct.PrimaryProducer, 
                      dbo.Latest_All_Lines_View_1_Oct.PrimaryProducerType
FROM         dbo.Latest_All_Lines_View_1_Oct LEFT OUTER JOIN
                      dbo.Policy_Information_GL_AVG_RATES_October ON 
                      dbo.Latest_All_Lines_View_1_Oct.policynumber = dbo.Policy_Information_GL_AVG_RATES_October.Policynumber
WHERE     (dbo.Latest_All_Lines_View_1_Oct.productcode = ''hc'')
' 
GO
