IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Latest_Policy_Information_GL_AVG_RATES_View_1]'))
DROP VIEW [dbo].[Latest_Policy_Information_GL_AVG_RATES_View_1]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[Latest_Policy_Information_GL_AVG_RATES_View_1]'))
EXEC dbo.sp_executesql @statement = N'CREATE view dbo.Latest_Policy_Information_GL_AVG_RATES_View_1
AS
SELECT     Policynumber, Amusement_Centers_Class_Group, Amusement_Centers_Premium, Amusement_Centers_Exposure, Amusement_Centers_Exposure_Adj, 
                      Amusement_Centers_Avg_Rate, Amusement_Centers_Avg_Rate_Range, Amusement_Parks_Class_Group, Amusement_Parks_Premium, 
                      Amusement_Parks_Exposure, Amusement_Parks_Exposure_Adj, Amusement_Parks_Avg_Rate, Amusement_Parks_Avg_Rate_Range, Apartments_Class_Group, 
                      Apartments_Premium, Apartments_Exposure, Apartments_Exposure_Adj, Apartments_Avg_Rate, Apartments_Avg_Rate_Range, Apartments_Garden_Class_Group, 
                      Apartments_Garden_Premium, Apartments_Garden_Exposure, Apartments_Garden_Exposure_Adj, Apartments_Garden_Avg_Rate, 
                      Apartments_Garden_Avg_Rate_Range, Apt_Outside_NY_Class_Group, Apt_Outside_NY_Premium, Apt_Outside_NY_Exposure, Apt_Outside_NY_Exposure_Adj, 
                      Apt_Outside_NY_Avg_Rate, Apt_Outside_NY_Avg_Rate_Range, Athletic_Programs_Class_Group, Athletic_Programs_Premium, Athletic_Programs_Exposure, 
                      Athletic_Programs_Exposure_Adj, Athletic_Programs_Avg_Rate, Athletic_Programs_Avg_Rate_Range, Bank_Office_FP_Class_Group, Bank_Office_FP_Premium, 
                      Bank_Office_FP_Exposure, Bank_Office_FP_Exposure_Adj, Bank_Office_FP_Avg_Rate, Bank_Office_FP_Avg_Rate_Range, Bank_Office_SelfMtd_FP_Class_Group, 
                      Bank_Office_SelfMtd_FP_Premium, Bank_Office_SelfMtd_FP_Exposure, Bank_Office_SelfMtd_FP_Exposure_Adj, Bank_Office_SelfMtd_FP_Avg_Rate, 
                      Bank_Office_SelfMtd_FP_Avg_Rate_Range, Boarding_Rooming_House_Class_Group, Boarding_Rooming_House_Premium, Boarding_Rooming_House_Exposure, 
                      Boarding_Rooming_House_Exposure_Adj, Boarding_Rooming_House_Avg_Rate, Boarding_Rooming_House_Avg_Rate_Range, Camps_Class_Group, 
                      Camps_Premium, Camps_Exposure, Camps_Exposure_Adj, Camps_Avg_Rate, Camps_Avg_Rate_Range, Camps_FP_Class_Group, Camps_FP_Premium, 
                      Camps_FP_Exposure, Camps_FP_Exposure_Adj, Camps_FP_Avg_Rate, Camps_FP_Avg_Rate_Range, Camps_NP_Class_Group, Camps_NP_Premium, 
                      Camps_NP_Exposure, Camps_NP_Exposure_Adj, Camps_NP_Avg_Rate, Camps_NP_Avg_Rate_Range, Churches_Class_Group, Churches_Premium, 
                      Churches_Exposure, Churches_Exposure_Adj, Churches_Avg_Rate, Churches_Avg_Rate_Range, Clubs_Class_Group, Clubs_Premium, Clubs_Exposure, 
                      Clubs_Exposure_Adj, Clubs_Avg_Rate, Clubs_Avg_Rate_Range, College_Class_Group, College_Premium, College_Exposure, College_Exposure_Adj, 
                      College_Avg_Rate, College_Avg_Rate_Range, College_FP_Class_Group, College_FP_Premium, College_FP_Exposure, College_FP_Exposure_Adj, 
                      College_FP_Avg_Rate, College_FP_Avg_Rate_Range, College_NP_Class_Group, College_NP_Premium, College_NP_Exposure, College_NP_Exposure_Adj, 
                      College_NP_Avg_Rate, College_NP_Avg_Rate_Range, Concessionaires_Class_Group, Concessionaires_Premium, Concessionaires_Exposure, 
                      Concessionaires_Exposure_Adj, Concessionaires_Avg_Rate, Concessionaires_Avg_Rate_Range, Condo_Association_Class_Group, Condo_Association_Premium, 
                      Condo_Association_Exposure, Condo_Association_Exposure_Adj, Condo_Association_Avg_Rate, Condo_Association_Avg_Rate_Range, 
                      Corp_Punishment_Class_Group, Corp_Punishment_Premium, Corp_Punishment_Exposure, Corp_Punishment_Exposure_Adj, Corp_Punishment_Avg_Rate, 
                      Corp_Punishment_Avg_Rate_Range, Day_Care_Class_Group, Day_Care_Premium, Day_Care_Exposure, Day_Care_Exposure_Adj, Day_Care_Avg_Rate, 
                      Day_Care_Avg_Rate_Range, Day_Care_FP_Class_Group, Day_Care_FP_Premium, Day_Care_FP_Exposure, Day_Care_FP_Exposure_Adj, Day_Care_FP_Avg_Rate, 
                      Day_Care_FP_Avg_Rate_Range, Day_Care_NP_Class_Group, Day_Care_NP_Premium, Day_Care_NP_Exposure, Day_Care_NP_Exposure_Adj, 
                      Day_Care_NP_Avg_Rate, Day_Care_NP_Avg_Rate_Range, Dormitories_Class_Group, Dormitories_Premium, Dormitories_Exposure, Dormitories_Exposure_Adj, 
                      Dormitories_Avg_Rate, Dormitories_Avg_Rate_Range, Dormitories_FP_Class_Group, Dormitories_FP_Premium, Dormitories_FP_Exposure, 
                      Dormitories_FP_Exposure_Adj, Dormitories_FP_Avg_Rate, Dormitories_FP_Avg_Rate_Range, Dormitories_NP_Class_Group, Dormitories_NP_Premium, 
                      Dormitories_NP_Exposure, Dormitories_NP_Exposure_Adj, Dormitories_NP_Avg_Rate, Dormitories_NP_Avg_Rate_Range, Driving_Range_Class_Group, 
                      Driving_Range_Premium, Driving_Range_Exposure, Driving_Range_Exposure_Adj, Driving_Range_Avg_Rate, Driving_Range_Avg_Rate_Range, 
                      Dwellings_Single_Fam_Class_Group, Dwellings_Single_Fam_Premium, Dwellings_Single_Fam_Exposure, Dwellings_Single_Fam_Exposure_Adj, 
                      Dwellings_Single_Fam_Avg_Rate, Dwellings_Single_Fam_Avg_Rate_Range, Exhibition_Bldgs_Class_Group, Exhibition_Bldgs_Premium, 
                      Exhibition_Bldgs_Exposure, Exhibition_Bldgs_Exposure_Adj, Exhibition_Bldgs_Avg_Rate, Exhibition_Bldgs_Avg_Rate_Range, Exhibitions_Class_Group, 
                      Exhibitions_Premium, Exhibitions_Exposure, Exhibitions_Exposure_Adj, Exhibitions_Avg_Rate, Exhibitions_Avg_Rate_Range, Golf_Municipal_Public_Class_Group, 
                      Golf_Municipal_Public_Premium, Golf_Municipal_Public_Exposure, Golf_Municipal_Public_Exposure_Adj, Golf_Municipal_Public_Avg_Rate, 
                      Golf_Municipal_Public_Avg_Rate_Range, Golf_Club_Country_Club_Class_Group, Golf_Club_Country_Club_Premium, Golf_Club_Country_Club_Exposure, 
                      Golf_Club_Country_Club_Exposure_Adj, Golf_Club_Country_Club_Avg_Rate, Golf_Club_Country_Club_Avg_Rate_Range, Guides_Outfitters_Class_Group, 
                      Guides_Outfitters_Premium, Guides_Outfitters_Exposure, Guides_Outfitters_Exposure_Adj, Guides_Outfitters_Avg_Rate, Guides_Outfitters_Avg_Rate_Range, 
                      HCF_AlcoholDrug_NP_Class_Group, HCF_AlcoholDrug_NP_Premium, HCF_AlcoholDrug_NP_Exposure, HCF_AlcoholDrug_NP_Exposure_Adj, 
                      HCF_AlcoholDrug_NP_Avg_Rate, HCF_AlcoholDrug_NP_Avg_Rate_Range, HCF_Homes_For_Aged_FP_Class_Group, HCF_Homes_For_Aged_FP_Premium, 
                      HCF_Homes_For_Aged_FP_Exposure, HCF_Homes_For_Aged_FP_Exposure_Adj, HCF_Homes_For_Aged_FP_Avg_Rate, 
                      HCF_Homes_For_Aged_FP_Avg_Rate_Range, HCF_Homes_For_Aged_NP_Class_Group, HCF_Homes_For_Aged_NP_Premium, 
                      HCF_Homes_For_Aged_NP_Exposure, HCF_Homes_For_Aged_NP_Exposure_Adj, HCF_Homes_For_Aged_NP_Avg_Rate, 
                      HCF_Homes_For_Aged_NP_Avg_Rate_Range, HCF_Phys_Handicap_FP_Class_Group, HCF_Phys_Handicap_FP_Premium, HCF_Phys_Handicap_FP_Exposure, 
                      HCF_Phys_Handicap_FP_Exposure_Adj, HCF_Phys_Handicap_FP_Avg_Rate, HCF_Phys_Handicap_FP_Avg_Rate_Range, HCF_Phys_Handicap_NP_Class_Group, 
                      HCF_Phys_Handicap_NP_Premium, HCF_Phys_Handicap_NP_Exposure, HCF_Phys_Handicap_NP_Exposure_Adj, HCF_Phys_Handicap_NP_Avg_Rate, 
                      HCF_Phys_Handicap_NP_Avg_Rate_Range, HCF_Psycopathic_NP_Class_Group, HCF_Psycopathic_NP_Premium, HCF_Psycopathic_NP_Exposure, 
                      HCF_Psycopathic_NP_Exposure_Adj, HCF_Psycopathic_NP_Avg_Rate, HCF_Psycopathic_NP_Avg_Rate_Range, Health_Exercise_Club_Class_Group, 
                      Health_Exercise_Club_Premium, Health_Exercise_Club_Exposure, Health_Exercise_Club_Exposure_Adj, Health_Exercise_Club_Avg_Rate, 
                      Health_Exercise_Club_Avg_Rate_Range, HomeHealthCare_Class_Group, HomeHealthCare_Premium, HomeHealthCare_Exposure, HomeHealthCare_Exposure_Adj, 
                      HomeHealthCare_Avg_Rate, HomeHealthCare_Avg_Rate_Range, HomeHealthCareNonSales_Class_Group, HomeHealthCareNonSales_Premium, 
                      HomeHealthCareNonSales_Exposure, HomeHealthCareNonSales_Exposure_Adj, HomeHealthCareNonSales_Avg_Rate, HomeHealthCareNonSales_Avg_Rate_Range, 
                      HomeHealthCareSales_Class_Group, HomeHealthCareSales_Premium, HomeHealthCareSales_Exposure, HomeHealthCareSales_Exposure_Adj, 
                      HomeHealthCareSales_Avg_Rate, HomeHealthCareSales_Avg_Rate_Range, Homeowner_Assoc_Class_Group, Homeowner_Assoc_Premium, 
                      Homeowner_Assoc_Exposure, Homeowner_Assoc_Exposure_Adj, Homeowner_Assoc_Avg_Rate, Homeowner_Assoc_Avg_Rate_Range, HT_w_PB_GE4_Class_Group, 
                      HT_w_PB_GE4_Premium, HT_w_PB_GE4_Exposure, HT_w_PB_GE4_Exposure_Adj, HT_w_PB_GE4_Avg_Rate, HT_w_PB_GE4_Avg_Rate_Range, 
                      HT_w_PB_LT4_Class_Group, HT_w_PB_LT4_Premium, HT_w_PB_LT4_Exposure, HT_w_PB_LT4_Exposure_Adj, HT_w_PB_LT4_Avg_Rate, 
                      HT_w_PB_LT4_Avg_Rate_Range, HT_wo_PB_GE4_Class_Group, HT_wo_PB_GE4_Premium, HT_wo_PB_GE4_Exposure, HT_wo_PB_GE4_Exposure_Adj, 
                      HT_wo_PB_GE4_Avg_Rate, HT_wo_PB_GE4_Avg_Rate_Range, HT_wo_PB_LT4_Class_Group, HT_wo_PB_LT4_Premium, HT_wo_PB_LT4_Exposure, 
                      HT_wo_PB_LT4_Exposure_Adj, HT_wo_PB_LT4_Avg_Rate, HT_wo_PB_LT4_Avg_Rate_Range, Hotels_Class_Group, Hotels_Premium, Hotels_Exposure, 
                      Hotels_Exposure_Adj, Hotels_Avg_Rate, Hotels_Avg_Rate_Range, Indoor_play_centers_Class_Group, Indoor_play_centers_Premium, 
                      Indoor_play_centers_Exposure, Indoor_play_centers_Exposure_Adj, Indoor_play_centers_Avg_Rate, Indoor_play_centers_Avg_Rate_Range, 
                      Janitorial_Services_Class_Group, Janitorial_Services_Premium, Janitorial_Services_Exposure, Janitorial_Services_Exposure_Adj, Janitorial_Services_Avg_Rate, 
                      Janitorial_Services_Avg_Rate_Range, Lakes_Resevoirs_Class_Group, Lakes_Resevoirs_Premium, Lakes_Resevoirs_Exposure, Lakes_Resevoirs_Exposure_Adj, 
                      Lakes_Resevoirs_Avg_Rate, Lakes_Resevoirs_Avg_Rate_Range, Miniature_Golf_Class_Group, Miniature_Golf_Premium, Miniature_Golf_Exposure, 
                      Miniature_Golf_Exposure_Adj, Miniature_Golf_Avg_Rate, Miniature_Golf_Avg_Rate_Range, Mobile_Home_Parks_Class_Group, Mobile_Home_Parks_Premium, 
                      Mobile_Home_Parks_Exposure, Mobile_Home_Parks_Exposure_Adj, Mobile_Home_Parks_Avg_Rate, Mobile_Home_Parks_Avg_Rate_Range, 
                      Offices_FP_Class_Group, Offices_FP_Premium, Offices_FP_Exposure, Offices_FP_Exposure_Adj, Offices_FP_Avg_Rate, Offices_FP_Avg_Rate_Range, 
                      Offices_NP_Class_Group, Offices_NP_Premium, Offices_NP_Exposure, Offices_NP_Exposure_Adj, Offices_NP_Avg_Rate, Offices_NP_Avg_Rate_Range, 
                      Outpatient_NP_Class_Group, Outpatient_NP_Premium, Outpatient_NP_Exposure, Outpatient_NP_Exposure_Adj, Outpatient_NP_Avg_Rate, 
                      Outpatient_NP_Avg_Rate_Range, Parks_Playgrounds_Class_Group, Parks_Playgrounds_Premium, Parks_Playgrounds_Exposure, 
                      Parks_Playgrounds_Exposure_Adj, Parks_Playgrounds_Avg_Rate, Parks_Playgrounds_Avg_Rate_Range, Private_HS_NP_Class_Group, Private_HS_NP_Premium, 
                      Private_HS_NP_Exposure, Private_HS_NP_Exposure_Adj, Private_HS_NP_Avg_Rate, Private_HS_NP_Avg_Rate_Range, Private_Parking_Class_Group, 
                      Private_Parking_Premium, Private_Parking_Exposure, Private_Parking_Exposure_Adj, Private_Parking_Avg_Rate, Private_Parking_Avg_Rate_Range, 
                      Private_Pre_HS_FP_Class_Group, Private_Pre_HS_FP_Premium, Private_Pre_HS_FP_Exposure, Private_Pre_HS_FP_Exposure_Adj, Private_Pre_HS_FP_Avg_Rate, 
                      Private_Pre_HS_FP_Avg_Rate_Range, Private_Pre_HS_NP_Class_Group, Private_Pre_HS_NP_Premium, Private_Pre_HS_NP_Exposure, 
                      Private_Pre_HS_NP_Exposure_Adj, Private_Pre_HS_NP_Avg_Rate, Private_Pre_HS_NP_Avg_Rate_Range, Private_Schools_Class_Group, 
                      Private_Schools_Premium, Private_Schools_Exposure, Private_Schools_Exposure_Adj, Private_Schools_Avg_Rate, Private_Schools_Avg_Rate_Range, 
                      Private_Schools_FP_Class_Group, Private_Schools_FP_Premium, Private_Schools_FP_Exposure, Private_Schools_FP_Exposure_Adj, 
                      Private_Schools_FP_Avg_Rate, Private_Schools_FP_Avg_Rate_Range, Public_Schools_Class_Group, Public_Schools_Premium, Public_Schools_Exposure, 
                      Public_Schools_Exposure_Adj, Public_Schools_Avg_Rate, Public_Schools_Avg_Rate_Range, Public_Schools_HS_Class_Group, Public_Schools_HS_Premium, 
                      Public_Schools_HS_Exposure, Public_Schools_HS_Exposure_Adj, Public_Schools_HS_Avg_Rate, Public_Schools_HS_Avg_Rate_Range, 
                      Public_Schools_Pre_HS_Class_Group, Public_Schools_Pre_HS_Premium, Public_Schools_Pre_HS_Exposure, Public_Schools_Pre_HS_Exposure_Adj, 
                      Public_Schools_Pre_HS_Avg_Rate, Public_Schools_Pre_HS_Avg_Rate_Range, Race_Tracks_Class_Group, Race_Tracks_Premium, Race_Tracks_Exposure, 
                      Race_Tracks_Exposure_Adj, Race_Tracks_Avg_Rate, Race_Tracks_Avg_Rate_Range, Sales_Service_Orgs_Class_Group, Sales_Service_Orgs_Premium, 
                      Sales_Service_Orgs_Exposure, Sales_Service_Orgs_Exposure_Adj, Sales_Service_Orgs_Avg_Rate, Sales_Service_Orgs_Avg_Rate_Range, 
                      Schools_FP_Class_Group, Schools_FP_Premium, Schools_FP_Exposure, Schools_FP_Exposure_Adj, Schools_FP_Avg_Rate, Schools_FP_Avg_Rate_Range, 
                      Schools_NP_Class_Group, Schools_NP_Premium, Schools_NP_Exposure, Schools_NP_Exposure_Adj, Schools_NP_Avg_Rate, Schools_NP_Avg_Rate_Range, 
                      Shelter_Mission_HlfwHouse_Class_Group, Shelter_Mission_HlfwHouse_Premium, Shelter_Mission_HlfwHouse_Exposure, 
                      Shelter_Mission_HlfwHouse_Exposure_Adj, Shelter_Mission_HlfwHouse_Avg_Rate, Shelter_Mission_HlfwHouse_Avg_Rate_Range, Skating_Rinks_Class_Group, 
                      Skating_Rinks_Premium, Skating_Rinks_Exposure, Skating_Rinks_Exposure_Adj, Skating_Rinks_Avg_Rate, Skating_Rinks_Avg_Rate_Range, 
                      Stadiums_Class_Group, Stadiums_Premium, Stadiums_Exposure, Stadiums_Exposure_Adj, Stadiums_Avg_Rate, Stadiums_Avg_Rate_Range, 
                      Swimming_Pools_Class_Group, Swimming_Pools_Premium, Swimming_Pools_Exposure, Swimming_Pools_Exposure_Adj, Swimming_Pools_Avg_Rate, 
                      Swimming_Pools_Avg_Rate_Range, Vocational_Schools_Class_Group, Vocational_Schools_Premium, Vocational_Schools_Exposure, 
                      Vocational_Schools_Exposure_Adj, Vocational_Schools_Avg_Rate, Vocational_Schools_Avg_Rate_Range, YMCA_YWCA_Class_Group, YMCA_YWCA_Premium, 
                      YMCA_YWCA_Exposure, YMCA_YWCA_Exposure_Adj, YMCA_YWCA_Avg_Rate, YMCA_YWCA_Avg_Rate_Range
FROM         dbo.Policy_Information_GL_AVG_RATES_June
' 
GO
